Repository tektoncd/catalog, pull requests merged in 2019-12, with the labels that each got.

#157 Catalog tests should not be looping in case of failures
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#153 Adding the OWNERS and the Dockerfile of ansible-tower-cli's custom image
  ansible-tower-cli/Dockerfile
  ansible-tower-cli/OWNERS
Labels: approved, lgtm, size/S

#155 Add tkn to catalog.
  tkn/README.md
  tkn/tkn.yaml
Labels: approved, lgtm, size/M

#141 Add MAVEN Task to catalog
  maven/README.md
  maven/maven.yaml
  maven/tests/resources.yaml
  maven/tests/run.yaml
Labels: approved, lgtm, size/L

#159 Default go versions to latest
  golang/README.md
  golang/build.yaml
  golang/tests.yaml
Labels: approved, lgtm, size/XS

#150 Azure CLI Task
  azure-cli/README.md
  azure-cli/azure_cli.yaml
Labels: approved, lgtm, size/M

#164 Adding OWNERS File for azure-cli
  azure-cli/OWNERS
Labels: approved, lgtm, size/XS
