Repository tektoncd/catalog, pull requests merged in 2019-08, with the labels that each got.

#59 [docs] Add code type to codeblocks
  golang/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#61 Added task for Kubeval
  kubeval/README.md
  kubeval/kubeval.yaml
Labels: approved, lgtm, ok-to-test, size/M

#66 Support to set go11module in golang task
  golang/README.md
  golang/build.yaml
  golang/lint.yaml
  golang/tests.yaml
Labels: approved, lgtm, ok-to-test, size/S
