Repository tektoncd/catalog, pull requests merged in 2019-11, with the labels that each got.

#119 Tag Default Buildah Image as v1.11.0
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, lgtm, size/XS

#120 Be explicit about files being a string
  conftest/conftest.yaml
Labels: approved, lgtm, size/XS

#116 Add OWNERS file to buildpacks task
  buildpacks/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, ok-to-test, size/S

#122 Add a task for tower-cli command execution Closes #106
  ansible-tower-cli/README.md
  ansible-tower-cli/ansible-tower-cli-task.yaml
Labels: approved, lgtm, ok-to-test, size/L

#125 References latest kn release v0.10.0 in task
  kn/README.md
  kn/kn.yaml
Labels: approved, lgtm, size/XS

#130 Add @sbwsg as approver in catalog
  OWNERS
Labels: approved, lgtm, size/XS

#133 Add @chmouel as an OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#127 Linting yamls with yamllint 🏷
  .yamllint
  ansible-tower-cli/ansible-tower-cli-task.yaml
  argocd/argocd.yaml
  buildah/buildah.yaml
  buildkit-daemonless/buildkit-daemonless.yaml
  buildkit/deployment+service.privileged.yaml
  buildkit/deployment+service.rootless.yaml
  buildkit/task.yaml
  buildpacks/buildpacks-v3.yaml
  conftest/conftest.yaml
  conftest/helm-conftest.yaml
  golang/lint.yaml
  kaniko/kaniko.yaml
  knctl/knctl-deploy.yaml
  kubeval/kubeval.yaml
  openwhisk/openwhisk.yaml
  openwhisk/service-account.yaml
  s2i/s2i.yaml
Labels: approved, lgtm, size/L

#132 Bump plumbing to latest changes 🔗
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/pipelinerun-logs/cmd/http/kodata/templates
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#135 Refactor e2e test
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#128 Add securityContext to run as root for kaniko task 🤖
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#137 Refactor the test functions
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#138 Add info about yaml validation in github/pull_req_template
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#142 Fix running s2i binary as user
  s2i/Dockerfile
Labels: approved, lgtm, size/XS

#143 Fix S2I E2E Test
  s2i/s2i.yaml
  s2i/tests/resources.yaml
  s2i/tests/run.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#146 [E2E] Add common function when we are adding a registry to tasks
  buildah/tests/pre-apply-task-hook.sh
  jib-maven/tests/pre-apply-task-hook.sh
  kaniko/tests/pre-apply-task-hook.sh
  s2i/tests/pre-apply-task-hook.sh
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#149 Add a task for terraform-cli command execution Closes #124
  terraform-cli/Dockerfile
  terraform-cli/OWNERS
  terraform-cli/README.md
  terraform-cli/terraform-cli-task.yaml
Labels: approved, lgtm, size/L

#152 Extract the builder image as a common parameter
  kaniko/kaniko.yaml
Labels: approved, lgtm, ok-to-test, size/XS
