Repository tektoncd/catalog, pull requests merged in 2019-06, with the labels that each got.

#40 Bump tektoncd/plumbing with latest fixes
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#34 Initial `knctl` task definition 🌮
  knctl/README.md
  knctl/knctl-deploy.yaml
Labels: approved, lgtm, size/M

#43 Initial golang tasks
  golang/README.md
  golang/build.yaml
  golang/lint.yaml
  golang/tests.yaml
Labels: approved, lgtm, size/L

#48 Change buildah image to official repository
  buildah/README.md
  buildah/buildah.yaml
  s2i/s2i.yaml
Labels: approved, lgtm, size/XS

#49 New Task: Argo CD
  argocd/README.md
  argocd/argocd.yaml
Labels: approved, lgtm, size/L
