Repository tektoncd/catalog, pull requests merged in 2019-05, with the labels that each got.

#16 Fix typo in buildpacks/README.md
  buildpacks/README.md
Labels: approved, lgtm, size/XS

#14 Add more documentation on development/contributing new submissions.
  DEVELOPMENT.md
Labels: approved, lgtm, size/M

#15 Adding a Task for jib-maven
  jib-maven/README.md
  jib-maven/jib-maven.yaml
Labels: approved, lgtm, size/L

#18 Use run image as image in export step
  buildpacks/buildpacks-v3.yaml
Labels: approved, lgtm, size/XS

#21 Remove bazel from the catalog.
  bazel/README.md
  bazel/bazel.yaml
Labels: approved, lgtm, size/M

#22 kaniko: set DOCKER_CONFIG
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#23 Add the required boilerplate to run presubmit tests in prow.
  Gopkg.lock
  Gopkg.toml
  test/integration_test.go
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/LICENSE
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XXL

#20 Add BuildKit Task
  buildkit/0-buildkitd.yaml
  buildkit/1-task.yaml
  buildkit/README.md
Labels: approved, lgtm, size/L

#24 Use tektoncd/plumbing instead of knative/test-infra
  Gopkg.lock
  Gopkg.toml
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/tektoncd/plumbing/LICENSE
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/markdown-link-check-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/markdown-lint-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XL

#25 Remove comments from Gopkg.toml and refer to the documentation
  Gopkg.toml
Labels: approved, lgtm, size/S

#27 Add a basic Task CRD validation test for all Tasks in the catalog.
  makisu/README.md
  makisu/registry.yaml
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#30 Fix the typo in buildah example
  buildah/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#32 Add a specific version and context support for kaniko
  kaniko/README.md
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/S

#35 Updated openshift-client task docs (serviceaccount, examples, etc)
  openshift-client/README.md
  openshift-client/openshift-client-kubecfg-task.yaml
  openshift-client/openshift-client-task.yaml
  openshift-client/taskUsingClusterResource/ocpipeline.yaml
  openshift-client/taskUsingClusterResource/ocpipelinerun.yaml
  openshift-client/taskUsingClusterResource/resource.yaml
  openshift-client/taskUsingServiceaccount/ocpipeline.yaml
  openshift-client/taskUsingServiceaccount/ocpipelinerun.yaml
  openshift-client/taskUsingServiceaccount/role.yaml
  openshift-client/taskUsingServiceaccount/rolebinding.yaml
  openshift-client/taskUsingServiceaccount/serviceaccount.yaml
Labels: approved, lgtm, size/L

#31 Add s2i task
  s2i/Dockerfile
  s2i/README.md
  s2i/examples/nodejs-s2i.yaml
  s2i/s2i.yaml
Labels: approved, lgtm, size/L
