Repository tektoncd/catalog, pull requests merged in 2019-10, with the labels that each got.

#92 Updated forgotten brackets with parentheses
  buildah/buildah.yaml
  buildkit/1-task.yaml
  openwhisk/openwhisk.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#93 Use quay.io/openshift/origin-cli instead of doing our own
  openshift-client/Dockerfile
Labels: approved, lgtm, size/S

#90 Add gcloud Task
  gcloud/README.md
  gcloud/gcloud.yaml
Labels: approved, lgtm, size/L

#98 Update kaniko executor image to 0.13.0
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#99 Update openshift client task for 0.7
  openshift-client/Dockerfile
  openshift-client/README.md
  openshift-client/openshift-client-kubecfg-task.yaml
  openshift-client/openshift-client-task.yaml
  openshift-client/script.sh
Labels: approved, lgtm, size/M

#100 Allow passing extra flags to kaniko
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#97 Bump tektoncd/plumbing dependency ⛽️
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#108 A new task related to Conftest which makes testing Helm charts easier
  conftest/README.md
  conftest/helm-conftest.yaml
Labels: approved, lgtm, size/M

#107 buildkit: use mTLS and suppport daemonless mode
  buildkit-daemonless/README.md
  buildkit-daemonless/buildkit-daemonless.yaml
  buildkit/.gitignore
  buildkit/0-buildkitd.yaml
  buildkit/README.md
  buildkit/create-certs.sh
  buildkit/deployment+service.privileged.yaml
  buildkit/deployment+service.rootless.yaml
  buildkit/task.yaml
Labels: approved, lgtm, ok-to-test, size/L

#109 Follow up commit to resolve README issues for conftest tasks
  conftest/README.md
Labels: approved, lgtm, size/XS

#111 There needs to be an equals after the --env
  kn/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#114 Updates kn released image path and pins to v0.9.0
  kn/README.md
  kn/kn.yaml
Labels: approved, lgtm, size/XS

#115 Set slack link to contact info section for slack
  README.md
Labels: approved, lgtm, ok-to-test, size/XS
