Repository tektoncd/catalog, pull requests merged in 2019-09, with the labels that each got.

#60 Added task for Conftest
  conftest/README.md
  conftest/conftest.yaml
Labels: approved, lgtm, ok-to-test, size/L

#71 Fix(kn-create): Updates the default value for force flag
  kn/kn-create.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#69 Add bobcatfish to owners 👼
  OWNERS
Labels: approved, lgtm, size/XS

#75 Fix kn-create Task to pass args in accepted manner
  kn/kn-create.yaml
Labels: approved, lgtm, size/S

#84 Use stepTemplate instead of containerTemplate as it is now gone
  argocd/argocd.yaml
Labels: approved, lgtm, size/XS

#86 Update templating to use `$(…)` instead of `${…}`
  argocd/argocd.yaml
  buildah/buildah.yaml
  buildkit/1-task.yaml
  buildpacks/buildpacks-v3.yaml
  conftest/conftest.yaml
  golang/build.yaml
  golang/lint.yaml
  golang/tests.yaml
  jib-maven/jib-maven.yaml
  kaniko/kaniko.yaml
  knctl/knctl-deploy.yaml
  kubeval/kubeval.yaml
  makisu/makisu.yaml
  openshift-client/openshift-client-kubecfg-task.yaml
  openshift-client/openshift-client-task.yaml
  openwhisk/openwhisk.yaml
  s2i/s2i.yaml
Labels: approved, lgtm, size/L

#87 Do not initialize a GCP cluster if we run a local CI
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#88 Allow ignoring test if we like
  test/e2e-tests.sh
Labels: approved, lgtm, size/S
