Repository tektoncd/catalog, pull requests merged in 2020-04, with the labels that each got.

#249 Update README on master 😌
  README.md
Labels: approved, lgtm, size/XS

#250 Update README.md to point to master/v1alpha1 📖
  README.md
Labels: approved, lgtm, size/XS

#248 Fix script in Maven Task and settings.xml mounting
  maven/README.md
  maven/maven.yaml
  maven/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#255 Remove duplicate word from maven/README
  maven/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#254 fix markdown list
  maven/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#236 Add 2020 roadmap 🛣️
  README.md
  roadmap.md
Labels: approved, lgtm, size/S

#259 Add 2020 roadmap 🛣️
  README.md
  roadmap.md
Labels: approved, lgtm, size/S

#257 Improve Maven Task in v1beta1
  maven/README.md
  maven/maven.yaml
  maven/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#246 Add GCS Tasks to replace the GCS PipelineResources
  gcs/README.md
  gcs/gcs-create-bucket.yaml
  gcs/gcs-delete-bucket.yaml
  gcs/gcs-download.yaml
  gcs/gcs-upload.yaml
Labels: approved, lgtm, size/L

#261 Use "path" instead of "name" 👣
  gcs/README.md
  gcs/gcs-download.yaml
Labels: approved, lgtm, size/S

#263 Remove unnecessary auth workspace 💼
  pullrequest/pr.yaml
Labels: approved, lgtm, size/XS

#266 Handle TaskRun as well as PipelineRun tests
  CONTRIBUTING.md
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#270 Temporarly disable yamllint 😓
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#271 Correct knctl sample
  knctl/README.md
  knctl/knctl-deploy.yaml
Labels: approved, cla: yes, lgtm, size/XS

#247 Update buildpacks task platform API to 0.3
  buildpacks/README.md
  buildpacks/buildpacks-v3.yaml
  buildpacks/tests/run.yaml
Labels: approved, cla: yes, lgtm, size/M

#237 Add Kubectl example
  kubectl/README.md
  kubectl/clusterrolebinding.yaml
  kubectl/kubectl-deploy.yaml
  kubectl/taskrun.yaml
Labels: approved, lgtm, size/L

#277 git-clone: fix git-init flags
  git/git-clone.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#278 Add Kubectl sample, porting from version "v1alpha1"
  kubectl/README.md
  kubectl/clusterrolebinding.yaml
  kubectl/kubectl-deploy.yaml
  kubectl/taskrun.yaml
Labels: approved, cla: yes, lgtm, size/L

#262 Test GCS Tasks
  gcs/sample/gcs-sample.yaml
Labels: approved, cla: yes, lgtm, size/L

#252 Pin git-clone to the 0.11.0 version of git-init
  git/git-clone.yaml
Labels: approved, lgtm, size/XS

#264 the removed line fails if a checkout hasn't yet happened
  git/git-clone.yaml
Labels: approved, cla: yes, lgtm, size/XS

#283 Fix some typos in slack message
  slackmessage/README.md
  slackmessage/send-to-channel-slack.yaml
  slackmessage/send-to-webhook-slack.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#280 Bump imagedigestexporter to v0.11.1
  kaniko/kaniko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#274 Add Replace Tokens Task
  replace-tokens/README.md
  replace-tokens/replace-tokens.yaml
  replace-tokens/tests/configmap.yaml
  replace-tokens/tests/pre-apply-task-hook.sh
  replace-tokens/tests/resource.yaml
  replace-tokens/tests/run.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#260 Add Skopeo task
  skopeo/README.md
  skopeo/example/docker-secret.yaml
  skopeo/example/quay-secret.yaml
  skopeo/example/run.yaml
  skopeo/example/serviceaccount.yaml
  skopeo/skopeo.yaml
  skopeo/test/pre-apply-task-hook.sh
  skopeo/test/run.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#288 Begin to collect Task authoring recommendations
  recommendations.md
Labels: approved, lgtm, size/S

#290 Remove default git Task subdir 📁
  git/README.md
  git/git-clone.yaml
Labels: approved, lgtm, size/XS
