Repository tektoncd/catalog, pull requests merged in 2020-12, with the labels that each got.

#558 Add kn-apply task
  task/kn-apply/0.1/README.md
  task/kn-apply/0.1/kn-apply.yaml
  task/kn-apply/0.1/support/kn-deployer.yaml
  task/kn-apply/OWNERS
Labels: approved, lgtm, size/L

#580 Add a catalog task to run the OpenSSF Security Scorecard project.
  task/scorecard/0.1/README.md
  task/scorecard/0.1/scorecard.yaml
  task/scorecard/OWNERS
Labels: approved, lgtm, size/M

#597 Bump tekton pipeline version to 0.18.1
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.2/git-clone.yaml
  test/e2e-tests.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#598 Fix e2e: Test remaining tasks after parellelization
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#601 Bump Tekton Pipeline version to 0.19.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#602 Skipping maven tests in CI
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#603 Remove unnecessary sidecar in golang test
  task/golang-build/0.1/tests/pre-apply-task-hook.sh
  task/golang-test/0.1/tests/pre-apply-task-hook.sh
Labels: approved, lgtm, size/XS

#604 Fix e2e script to detect any file change
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS
