Repository tektoncd/catalog, pull requests merged in 2020-02, with the labels that each got.

#174 Add Github close issue/pr task
  github/README.md
  github/close_issue.yaml
Labels: approved, lgtm, size/L

#179 Update README and align the numbered list
  kn/knative-dockerfile-deploy/README.md
Labels: approved, lgtm, size/XS

#178 Update openshift client task to use script mode
  openshift-client/README.md
  openshift-client/openshift-client-kubecfg-task.yaml
  openshift-client/openshift-client-task.yaml
Labels: approved, lgtm, size/S

#123 Add a git task to clone a repository without PipelineResource
  git/README.md
  git/fetch-git.yaml
Labels: approved, lgtm, size/L

#175 Update CNB task to conform to Platform API 0.2
  buildpacks/README.md
  buildpacks/buildpacks-v3.yaml
Labels: approved, lgtm, ok-to-test, size/L

#182 Update the git fetch task to include all params used in the Git PipelineResource
  git/README.md
  git/fetch-git.yaml
  git/git-clone.yaml
Labels: approved, lgtm, size/L

#180 Send slack message tasks
  slackmessage/OWNERS
  slackmessage/README.md
  slackmessage/send-to-channel-slack.yaml
  slackmessage/send-to-webhook-slack.yaml
Labels: approved, lgtm, size/L

#183 Send email via SMTP server task
  mail/OWNERS
  mail/README.md
  mail/sendmail.yaml
Labels: approved, lgtm, size/L

#185 fix syntax error in the webhook task
  slackmessage/send-to-webhook-slack.yaml
Labels: approved, lgtm, size/XS

#186 Clarify requirements of git-clone Task
  git/README.md
Labels: approved, lgtm, size/M

#187 git-clone: Pass depth and sslVerify params to args
  git/git-clone.yaml
Labels: approved, lgtm, size/S

#192 Default kn image to the latest released version
  kn/kn.yaml
Labels: approved, lgtm, size/XS

#199 Fix jib-gradle task
  jib-gradle/jib-gradle.yaml
Labels: approved, lgtm, size/XS

#200 Run prepare of buildpack as privileged
  buildpacks/buildpacks-v3.yaml
Labels: approved, lgtm, size/XS
