Repository tektoncd/catalog, pull requests merged in 2020-03, with the labels that each got.

#205 Don't change Gradle home in jib-gradle
  jib-gradle/jib-gradle.yaml
Labels: approved, lgtm, size/XS

#204 Add a delete param to the git-clone task for reusing PVCs
  git/README.md
  git/git-clone.yaml
Labels: approved, lgtm, size/M

#209 Combine DEVELOPMENT.md and CONTRIBUTING.md
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/L

#208 Use script for golang tasks 🦍
  golang/build.yaml
  golang/lint.yaml
  golang/tests.yaml
Labels: approved, lgtm, size/S

#207 Use workingDir instead of workingdir 🐺
  conftest/conftest.yaml
  conftest/helm-conftest.yaml
  golang/build.yaml
  golang/lint.yaml
  golang/tests.yaml
  kaniko/kaniko.yaml
  kubeval/kubeval.yaml
  makisu/makisu.yaml
  maven/README.md
  maven/maven.yaml
  s2i/s2i.yaml
Labels: approved, lgtm, size/S

#210 Use golang instead of bazel in catalog README 📎
  README.md
Labels: approved, kind/documentation, lgtm, size/S

#212 Add Task equivalent of PullRequest PipelineResource ⚗️
  pullrequest/OWNERS
  pullrequest/README.md
  pullrequest/pr-example/README.md
  pullrequest/pr-example/base.json
  pullrequest/pr-example/comments/505233618.json
  pullrequest/pr-example/comments/505476017.json
  pullrequest/pr-example/comments/505482755.json
  pullrequest/pr-example/comments/505529049.json
  pullrequest/pr-example/comments/505616303.json
  pullrequest/pr-example/comments/505676294.json
  pullrequest/pr-example/comments/505798994.json
  pullrequest/pr-example/comments/505890656.json
  pullrequest/pr-example/comments/505923534.json
  pullrequest/pr-example/comments/506032472.json
  pullrequest/pr-example/comments/506082430.json
  pullrequest/pr-example/comments/506082465.json
  pullrequest/pr-example/comments/507732301.json
  pullrequest/pr-example/comments/507763725.json
  pullrequest/pr-example/comments/508007084.json
  pullrequest/pr-example/head.json
  pullrequest/pr-example/labels/approved
  pullrequest/pr-example/labels/cla%3A+yes
  pullrequest/pr-example/labels/lgtm
  pullrequest/pr-example/labels/size%2FL
  pullrequest/pr-example/pr.json
  pullrequest/pr-example/status/cla%2Fgoogle.json
  pullrequest/pr-example/status/pull-tekton-pipeline-build-tests.json
  pullrequest/pr-example/status/pull-tekton-pipeline-go-coverage.json
  pullrequest/pr-example/status/pull-tekton-pipeline-integration-tests.json
  pullrequest/pr-example/status/pull-tekton-pipeline-unit-tests.json
  pullrequest/pr-example/status/tide.json
  pullrequest/pr.yaml
  pullrequest/sample/add-comment.yaml
  pullrequest/sample/static.yaml
Labels: approved, lgtm, size/XL

#214 Run jib-gradle as root
  jib-gradle/jib-gradle.yaml
Labels: approved, lgtm, size/XS

#218 Update the pullrequest image
  pullrequest/pr.yaml
Labels: approved, lgtm, size/XS

#195 Github Enterprise support for github tasks
  github/README.md
  github/add_comment.yaml
  github/close_issue.yaml
  github/set_status.yaml
Labels: approved, lgtm, size/M

#222 Add --format option to buildah task
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#225 Add Pipelines version info to the git-clone README
  git/README.md
Labels: approved, lgtm, size/XS

#223 the removed line fails if a checkout hasn't yet happened
  git/git-clone.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#220 Add Proxies and use Script for maven tasks
  maven/README.md
  maven/maven.yaml
Labels: approved, lgtm, ok-to-test, size/L

#234 Force using v0.11.0-rc2 yaml for the v1beta1 branch
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#227 Use latest for kaniko task 😅
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#232 Add pipeline and pipelinerun for golang
  golang/README.md
  golang/build.yaml
  golang/lint.yaml
  golang/test/pre-apply-task-hook.sh
  golang/test/resources.yaml
  golang/test/run.yaml
  golang/tests.yaml
Labels: approved, lgtm, ok-to-test, size/M

#242 Update kn task for workspace to deploy successfully
  kn/knative-dockerfile-deploy/README.md
  kn/knative-dockerfile-deploy/build_deploy/README.md
  kn/knative-dockerfile-deploy/build_deploy/pipeline_run.yaml
  kn/knative-dockerfile-deploy/build_deploy/resources.yaml
Labels: approved, lgtm, size/M

#241 Add optional input resource of type git
  openshift-client/openshift-client-task.yaml
Labels: approved, lgtm, ok-to-test, size/XS
