Repository tektoncd/catalog, pull requests merged in 2020-06, with the labels that each got.

#341 Add SonarQube Task to catalog
  sonarqube/README.md
  sonarqube/examples/pvc.yaml
  sonarqube/examples/run.yaml
  sonarqube/examples/sonar-project.properties
  sonarqube/sonarqube.yaml
Labels: approved, lgtm, ok-to-test, size/L

#287 Add aws-cli task
  aws-cli/README.md
  aws-cli/aws-cli.yaml
  aws-cli/example/run.yaml
  aws-cli/example/secret.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#342 Improve existing OpenShift provision task
  openshift-provision/README.md
  openshift-provision/openshift-cluster-create.yaml
  openshift-provision/openshift-cluster-destroy.yaml
Labels: approved, lgtm, ok-to-test, size/M

#316 Add task to label Github pull request or an issue
  github/add-labels/README.md
  github/add-labels/add-labels.yaml
  github/add-labels/example/run.yaml
  github/add-labels/example/secret.yaml
Labels: approved, lgtm, ok-to-test, size/L

#321 Improve examples for the git-clone Task
  git/README.md
  git/examples/git-clone-checking-out-a-branch.yaml
  git/examples/git-clone-checking-out-a-commit.yaml
  git/examples/using-git-clone-result.yaml
Labels: approved, kind/documentation, lgtm, size/L

#330 Add support for merge requests in GitLab add-labels task
  gitlab/README.md
  gitlab/add-labels.yaml
Labels: approved, lgtm, ok-to-test, size/S

#256 Make sure we skip the test if there is no yaml file in there
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#308 Add Gitlab Release task
  gitlab/create-gitlab-release/README.md
  gitlab/create-gitlab-release/create-gitlab-release.yaml
  gitlab/create-gitlab-release/example/run.yaml
  gitlab/create-gitlab-release/example/secret.yaml
Labels: approved, lgtm, ok-to-test, size/L

#346 I'm an owner now!
  ibmcloud-cli/OWNERS
Labels: approved, lgtm, size/XS

#360 Add a "Run as non root" recommandation…
  recommendations.md
Labels: approved, lgtm, size/M

#362 A yellow warning for legcacy issue template was there
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: approved, lgtm, size/S

#355 create curl task to request response from internet
  curl/README.md
  curl/curl.yaml
  curl/tests/run.yaml
Labels: approved, lgtm, size/L

#365 Pin maven repo test to a revision
  maven/tests/run.yaml
Labels: approved, lgtm, size/XS

#344 Task to publish python module to PyPI
  python/publish-package/README.md
  python/publish-package/example/run.yaml
  python/publish-package/tests/pre-apply-task-hook.sh
  python/publish-package/tests/run.yaml
  python/publish-package/update-pypi.yaml
Labels: approved, lgtm, ok-to-test, size/L

#351 Create a new Prettier task version 1
  prettier/README.md
  prettier/prettier.yaml
  prettier/tests/pre-apply-task-hook.sh
  prettier/tests/resources.yaml
  prettier/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#301 (master -> v1beta1) Add Kythe golang extractor task.
  kythe/README.md
  kythe/kythe-go.yaml
  kythe/tests/run.yaml
Labels: approved, kind/feature, lgtm, size/M

#374 Update automation to test against 0.13.2
  test/e2e-tests.sh
Labels: approved, kind/misc, lgtm, size/XS

#380 Wait until all TaskRuns are complete to print logs
  test/e2e-common.sh
Labels: approved, kind/bug, lgtm, size/XS

#383 test-runner: Do not show logs on success
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#378 Bump git-init image to 0.13.2
  git/git-batch-merge.yaml
  git/git-clone.yaml
Labels: approved, lgtm, size/XS

#325 Add Git Rebase task
  git/README.md
  git/examples/git-rebase/run.yaml
  git/examples/git-rebase/secret.yaml
  git/examples/git-rebase/service-account.yaml
  git/git-rebase.yaml
Labels: approved, lgtm, ok-to-test, size/L
