Repository tektoncd/catalog, pull requests merged in 2020-07, with the labels that each got.

#392 Add Git CLI task
  git/README.md
  git/examples/git-cli/pipeline.yaml
  git/examples/git-cli/pvc.yaml
  git/examples/git-cli/secret.yaml
  git/examples/git-cli/service-account.yaml
  git/git-cli.yaml
  git/tests/run.yaml
Labels: approved, lgtm, size/L

#398 Improve the README in master branch
  argocd/README.md
  aws-cli/README.md
  azure-cli/README.md
  buildah/README.md
  buildid/README.md
  buildkit-daemonless/README.md
  buildpacks/README.md
  conftest/README.md
  curl/README.md
  gcloud/README.md
  github/README.md
  gitlab/README.md
  gke-deploy/README.md
  golang/README.md
  jib-gradle/README.md
  jib-maven/README.md
  kaniko/README.md
  kn/README.md
  knctl/README.md
  kubeconfig-creator/README.md
  kubeval/README.md
  mail/README.md
  makisu/README.md
  maven/README.md
  openshift-client-python/README.md
  openshift-client/README.md
  openshift-provision/README.md
  replace-tokens/README.md
  s2i/README.md
  skopeo/README.md
  slackmessage/README.md
  sonarqube/README.md
  telegrammessage/README.md
  terraform-cli/README.md
  tkn/README.md
  wget/README.md
Labels: approved, lgtm, ok-to-test, size/M

#403 Update READMEs of tasks using workspaces in place of PipelineResources
  buildah/README.md
  buildkit-daemonless/README.md
  buildkit/README.md
  conftest/README.md
  golang/README.md
  helm/README.md
  jib-gradle/README.md
  jib-maven/README.md
  kaniko/README.md
  kubeval/README.md
  makisu/README.md
  python/publish-package/README.md
  s2i/README.md
  terraform-cli/README.md
Labels: approved, kind/cleanup, lgtm, size/M

#402 Updated helm catalog to allow for helm charts to be deployed from hel…
  helm/README.md
  helm/example/helm-upgrade-from-repo-task-run.yaml.tmpl
  helm/example/helm-upgrade-from-source-task-run.yaml.tmpl
  helm/helm-upgrade-from-repo.yaml
  helm/helm-upgrade-from-source.yaml
  helm/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#406 Add support for passing extra args to the buildah commands.
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, lgtm, size/S

#414 Add manual validation checks to comply with Catalog Org TEP
  .github/pull_request_template.md
Labels: approved, lgtm, size/S

#404 Remove word "volume" from "Workspace volume" in READMEs
  task/buildah/0.1/README.md
  task/buildkit-daemonless/0.1/README.md
  task/buildkit/0.1/README.md
  task/conftest/0.1/README.md
  task/golang-build/0.1/README.md
  task/golang-test/0.1/README.md
  task/golangci-lint/0.1/README.md
  task/helm-conftest/0.1/README.md
  task/helm-upgrade-from-source/0.1/README.md
  task/jib-gradle/0.1/README.md
  task/jib-maven/0.1/README.md
  task/kaniko/0.1/README.md
  task/kubeval/0.1/README.md
  task/makisu/0.1/README.md
  task/s2i/0.1/README.md
  task/terraform-cli/0.1/README.md
  task/upload-pypi/0.1/README.md
Labels: approved, kind/cleanup, lgtm, size/M

#418 Modifies the path in readme for samples directory
  task/aws-cli/0.1/README.md
  task/build-push-gke-deploy/0.1/README.md
  task/create-github-release/0.1/README.md
  task/create-gitlab-release/0.1/README.md
  task/generate-build-id/0.1/README.md
  task/git-cli/0.1/README.md
  task/git-clone/0.1/README.md
  task/git-rebase/0.1/README.md
  task/github-add-labels/0.1/README.md
  task/gke-deploy/0.1/README.md
  task/kubeconfig-creator/0.1/README.md
  task/pull-request/0.1/README.md
  task/skopeo-copy/0.1/README.md
  task/sonarqube-scanner/0.1/README.md
Labels: approved, lgtm, size/M

#425 Bump skopeo image to point to the official one
  task/skopeo-copy/0.1/skopeo-copy.yaml
Labels: approved, lgtm, size/XS

#397 Bump pipeline release to 0.14.0
  task/git-batch-merge/0.1/git-batch-merge.yaml
  task/git-clone/0.1/git-clone.yaml
  task/kaniko/0.1/kaniko.yaml
  task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
  task/pull-request/0.1/pull-request.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#426 updating raw Task URL in kubectl-deploy-pod readme
  task/kubectl-deploy-pod/0.1/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#428 Use python3
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#367 Add kubernetes actions task in `kubectl`
  task/kubernetes-actions/0.1/README.md
  task/kubernetes-actions/0.1/kubernetes-actions.yaml
  task/kubernetes-actions/0.1/samples/kubectl-actions-run.yaml
  task/kubernetes-actions/0.1/samples/update-deployment-image-taskrun.yaml
Labels: approved, lgtm, ok-to-test, size/L

#431 Refactor sidecar script
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#407 Make jib-gradle and jib-maven future-proof regarding Tekton $HOME deprecation
  task/jib-gradle/0.1/README.md
  task/jib-gradle/0.1/jib-gradle.yaml
  task/jib-maven/0.1/README.md
  task/jib-maven/0.1/jib-maven.yaml
Labels: approved, lgtm, size/M

#432 Add pylint and pytest task
  task/pylint/0.1/README.md
  task/pylint/0.1/pylint.yaml
  task/pylint/0.1/tests/pre-apply-task-hook.sh
  task/pylint/0.1/tests/resources.yaml
  task/pylint/0.1/tests/run.yaml
  task/pytest/0.1/README.md
  task/pytest/0.1/pytest.yaml
  task/pytest/0.1/tests/pre-apply-task-hook.sh
  task/pytest/0.1/tests/resources.yaml
  task/pytest/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#438 Fix kythe-go task on restricted environment
  task/kythe-go/0.1/kythe-go.yaml
  task/kythe-go/0.1/tests/run.yaml
Labels: approved, lgtm, size/XS

#443 Make OWNERS own all versions of a resource
  task/ansible-tower-cli/OWNERS
  task/az/OWNERS
  task/bentoml/OWNERS
  task/buildah/OWNERS
  task/buildpacks-phases/OWNERS
  task/buildpacks/OWNERS
  task/conftest/OWNERS
  task/generate-build-id/OWNERS
  task/golang-build/OWNERS
  task/golang-test/OWNERS
  task/golangci-lint/OWNERS
  task/helm-conftest/OWNERS
  task/helm-upgrade-from-repo/OWNERS
  task/helm-upgrade-from-source/OWNERS
  task/ibmcloud/OWNERS
  task/jib-gradle/OWNERS
  task/jib-maven/OWNERS
  task/kn/OWNERS
  task/kubeval/OWNERS
  task/openshift-client-kubecfg/OWNERS
  task/openshift-client/OWNERS
  task/pull-request/OWNERS
  task/s2i/OWNERS
  task/send-to-channel-slack/OWNERS
  task/send-to-webhook-slack/OWNERS
  task/sendmail/OWNERS
  task/terraform-cli/OWNERS
Labels: approved, lgtm, size/XS

#436 Add a task for creating a GKE cluster for e2e tests 🧪
  task/gke-cluster-create/0.1/README.md
  task/gke-cluster-create/0.1/gke-cluster-create.yaml
  task/gke-cluster-create/0.1/samples/create-gke-cluster.yaml
  task/gke-cluster-create/OWNERS
Labels: approved, lgtm, size/L

#409 Create Docker Build task with sidecar in catalog
  task/docker-build/0.1/OWNERS
  task/docker-build/0.1/README.md
  task/docker-build/0.1/docker-build.yaml
  task/docker-build/0.1/samples/docker-build.yaml.tmpl
  task/docker-build/0.1/tests/pre-apply-task-hook.sh
  task/docker-build/0.1/tests/resources.yaml
  task/docker-build/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#429 Add task which can run shell commands on remote Host
  task/remote-ssh-commands/0.1/README.md
  task/remote-ssh-commands/0.1/remote-ssh-commands.yaml
  task/remote-ssh-commands/0.1/samples/run.yaml
  task/remote-ssh-commands/0.1/samples/secrets.yaml
Labels: approved, lgtm, size/L

#408 Add Tasks to acquire and release boskos resources 🐑
  task/boskos-acquire/0.1/README.md
  task/boskos-acquire/0.1/boskos-acquire.yaml
  task/boskos-acquire/0.1/samples/pipelinerun.yaml
  task/boskos-acquire/0.1/samples/service-account.yaml
  task/boskos-acquire/OWNERS
  task/boskos-release/0.1/README.md
  task/boskos-release/0.1/boskos-release.yaml
  task/boskos-release/0.1/samples/pipelinerun.yaml
  task/boskos-release/0.1/samples/service-account.yaml
  task/boskos-release/OWNERS
Labels: approved, lgtm, size/L

#445 Fix pytest and pylint task
  task/pylint/0.1/pylint.yaml
  task/pytest/0.1/pytest.yaml
Labels: approved, lgtm, size/S

#437 Centralize all the git-clone apply task to a common function
  CONTRIBUTING.md
  task/buildah/0.1/tests/pre-apply-task-hook.sh
  task/buildpacks-phases/0.1/tests/pre-apply-task-hook.sh
  task/buildpacks/0.1/tests/pre-apply-task-hook.sh
  task/golang-build/0.1/tests/pre-apply-task-hook.sh
  task/golang-test/0.1/tests/pre-apply-task-hook.sh
  task/golangci-lint/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-repo/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.1/tests/pre-apply-task-hook.sh
  task/jib-gradle/0.1/tests/pre-apply-task-hook.sh
  task/jib-maven/0.1/tests/pre-apply-task-hook.sh
  task/kaniko/0.1/tests/pre-apply-task-hook.sh
  task/maven/0.1/tests/pre-apply-task-hook.sh
  task/prettier/0.1/tests/pre-apply-task-hook.sh
  task/pylint/0.1/tests/pre-apply-task-hook.sh
  task/pytest/0.1/tests/pre-apply-task-hook.sh
  task/replace-tokens/0.1/tests/pre-apply-task-hook.sh
  task/s2i/0.1/tests/pre-apply-task-hook.sh
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#435 Parameterize maven task image
  task/maven/0.1/README.md
  task/maven/0.1/maven.yaml
Labels: approved, lgtm, size/XS

#399 Add AWS ECR Login task
  task/aws-ecr-login/0.1/README.md
  task/aws-ecr-login/0.1/aws-ecr-login.yaml
  task/aws-ecr-login/0.1/samples/run.yaml
  task/aws-ecr-login/0.1/samples/secret.yaml
  task/aws-ecr-login/0.1/samples/test-task.yaml
Labels: approved, lgtm, size/L

#451 Spell Error kubectl-deploy-pod.yaml
  task/kubectl-deploy-pod/0.1/kubectl-deploy-pod.yaml
Labels: approved, lgtm, size/XS

#391 Add Task to Trigger Jenkins Build using Tekton
  task/trigger-jenkins-job/0.1/README.md
  task/trigger-jenkins-job/0.1/samples/run.yaml
  task/trigger-jenkins-job/0.1/samples/secrets.yaml
  task/trigger-jenkins-job/0.1/trigger-jenkins-job.yaml
Labels: approved, lgtm, size/L

#375 Update openwhisk-knative pipeline to v1beta1
  pipeline/openwhisk/0.1/.gitignore
  pipeline/openwhisk/0.1/README.md
  pipeline/openwhisk/0.1/conditions/detect-runtimes.yaml
  pipeline/openwhisk/0.1/deploy.sh
  pipeline/openwhisk/0.1/docker-secret.yaml.tmpl
  pipeline/openwhisk/0.1/images/01-dice-color.png
  pipeline/openwhisk/0.1/images/01-dice-gray.png
  pipeline/openwhisk/0.1/images/02-conf-crowd-gray.png
  pipeline/openwhisk/0.1/images/02-conf-crowd.png
  pipeline/openwhisk/0.1/images/03-eclipsecon-2019-gray.png
  pipeline/openwhisk/0.1/images/03-eclipsecon-2019.png
  pipeline/openwhisk/0.1/images/04-java-duke.png
  pipeline/openwhisk/0.1/images/OpenWhisk-to-Knative-general-pipeline.png
  pipeline/openwhisk/0.1/images/Tekton-resource-relationships.png
  pipeline/openwhisk/0.1/images/java-pipeline-vision.jpg
  pipeline/openwhisk/0.1/images/pipeline-customized-for-java.png
  pipeline/openwhisk/0.1/images/pipeline-customized-for-nodejs.png
  pipeline/openwhisk/0.1/images/pipeline-customized-for-python.png
  pipeline/openwhisk/0.1/pipelinerun/java/01-dice-color.json
  pipeline/openwhisk/0.1/pipelinerun/java/02-conf-crowd.json
  pipeline/openwhisk/0.1/pipelinerun/java/pipelinerun-java.yaml.tmpl
  pipeline/openwhisk/0.1/pipelinerun/javascript/left-padding-data-run.json
  pipeline/openwhisk/0.1/pipelinerun/javascript/pipelinerun-javascript.yaml.tmpl
  pipeline/openwhisk/0.1/pipelinerun/python/pipelinerun-python.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/README.md
  pipeline/openwhisk/0.1/runtimes/javascript/examples/01-helloworld/service-helloworld.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/01-helloworld/taskrun-helloworld.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/02-json-in-json-out/service-helloworld-with-params.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/02-json-in-json-out/taskrun-helloworld-with-params.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/03-github/hello.js
  pipeline/openwhisk/0.1/runtimes/javascript/examples/03-github/service-raw-github.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/03-github/taskrun-raw-github.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/04-zip/action.zip
  pipeline/openwhisk/0.1/runtimes/javascript/examples/04-zip/service-zip.yaml.tmpl
  pipeline/openwhisk/0.1/runtimes/javascript/examples/04-zip/taskrun-zip.yaml.tmpl
  pipeline/openwhisk/0.1/service-account.yaml
  pipeline/openwhisk/0.1/services/service-openwhisk-java-app.yaml.tmpl
  pipeline/openwhisk/0.1/services/service-openwhisk-javascript-app.yaml.tmpl
  pipeline/openwhisk/0.1/services/service-openwhisk-python-app.yaml.tmpl
  pipeline/openwhisk/0.1/tasks/00-clone-app-repo.yaml
  pipeline/openwhisk/0.1/tasks/00-clone-runtime-repo.yaml
  pipeline/openwhisk/0.1/tasks/java/01-create-jar-with-maven.yaml
  pipeline/openwhisk/0.1/tasks/java/02-build-runtime-with-gradle.yaml
  pipeline/openwhisk/0.1/tasks/java/03-build-shared-class-cache.yaml
  pipeline/openwhisk/0.1/tasks/java/04-finalize-runtime-with-function.yaml
  pipeline/openwhisk/0.1/tasks/javascript/01-install-deps.yaml
  pipeline/openwhisk/0.1/tasks/javascript/02-build-archive.yaml
  pipeline/openwhisk/0.1/tasks/javascript/03-openwhisk.yaml
  pipeline/openwhisk/0.1/tasks/python/01-install-deps.yaml
  pipeline/openwhisk/0.1/tasks/python/02-build-archive.yaml
  pipeline/openwhisk/0.1/tasks/python/03-openwhisk.yaml
  pipeline/openwhisk/0.1/workspaces/persistent-volume-claim.yaml
  task/openwhisk/0.1/README.md
  task/openwhisk/0.1/docker-secret.yaml.tmpl
  task/openwhisk/0.1/openwhisk.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#456 Refractor kubectl-deploy-pod Task as per TEP
  task/kubectl-deploy-pod/0.1/README.md
  task/kubectl-deploy-pod/0.1/samples/taskrun-delete.yaml
  task/kubectl-deploy-pod/0.1/samples/taskrun.yaml
  task/kubectl-deploy-pod/0.1/support/clusterrole.yaml
  task/kubectl-deploy-pod/0.1/support/clusterrolebinding.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#458 Add task to include code coverage for Python
  task/python-coverage/0.1/README.md
  task/python-coverage/0.1/python-coverage.yaml
  task/python-coverage/0.1/tests/pre-apply-task-hook.sh
  task/python-coverage/0.1/tests/resources.yaml
  task/python-coverage/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#439 Fixes and improvements to the upload-pypi Task.
  task/upload-pypi/0.1/README.md
  task/upload-pypi/0.1/samples/run.yaml
  task/upload-pypi/0.1/upload-pypi.yaml
Labels: approved, lgtm, size/M

#440 Prometheus gate
  task/prometheus-gate/0.1/README.md
  task/prometheus-gate/0.1/prometheus-gate.yaml
  task/prometheus-gate/0.1/samples/README.md
  task/prometheus-gate/0.1/samples/pipeline.yaml
  task/prometheus-gate/0.1/samples/pipelinerun.yaml
Labels: approved, lgtm, size/L
