Repository tektoncd/catalog, pull requests merged in 2020-08, with the labels that each got.

#454 Refactor namespace name to have version
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#465 Fix README.md of skopeo task
  task/skopeo-copy/0.1/README.md
Labels: approved, lgtm, size/XS

#474 Remove "lint" checklist item 📝
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#475 Remove "end to end" from cluster creation Task
  task/gke-cluster-create/0.1/README.md
Labels: approved, lgtm, size/XS

#459 Fixes for pylint tasks
  task/pylint/0.1/pylint.yaml
Labels: approved, lgtm, size/S

#470 Fixes for python coverage and pytest and added OWNERS
  task/pylint/0.1/README.md
  task/pylint/0.1/pylint.yaml
  task/pylint/OWNERS
  task/pytest/0.1/README.md
  task/pytest/0.1/pytest.yaml
  task/pytest/OWNERS
  task/python-coverage/0.1/README.md
  task/python-coverage/0.1/python-coverage.yaml
  task/python-coverage/OWNERS
Labels: approved, lgtm, ok-to-test, size/M

#478 fix: git-batch-merge should default to depth=0 and subdirectory=""
  task/git-batch-merge/0.2/README.md
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-batch-merge/0.2/samples/git-cli/pipeline.yaml
  task/git-batch-merge/0.2/samples/git-cli/pvc.yaml
  task/git-batch-merge/0.2/samples/git-cli/secret.yaml
  task/git-batch-merge/0.2/samples/git-cli/service-account.yaml
  task/git-batch-merge/0.2/samples/git-clone-checking-out-a-branch.yaml
  task/git-batch-merge/0.2/samples/git-clone-checking-out-a-commit.yaml
  task/git-batch-merge/0.2/samples/git-rebase/run.yaml
  task/git-batch-merge/0.2/samples/git-rebase/secret.yaml
  task/git-batch-merge/0.2/samples/git-rebase/service-account.yaml
  task/git-batch-merge/0.2/samples/using-git-clone-result.yaml
  task/git-batch-merge/0.2/tests/run.yaml
Labels: approved, lgtm, size/XL

#464 Add Ansible Runner Task
  task/ansible-runner/0.1/README.md
  task/ansible-runner/0.1/ansible-runner.yaml
  task/ansible-runner/0.1/support/ansible-deployer.yaml
  task/ansible-runner/0.1/support/playbooks-pvc.yaml
  task/ansible-runner/0.1/tests/pre-apply-task-hook.sh
  task/ansible-runner/0.1/tests/resources.yaml
  task/ansible-runner/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#482 Add a helper script to run a task test directly on your local cluster
  CONTRIBUTING.md
  test/run-test.sh
Labels: approved, lgtm, size/M

#467 Fix links in README in Blue Green Deploy task
  task/blue-green-deploy/0.1/README.md
Labels: approved, lgtm, size/XS

#487 Skip docker-build in CI
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#486 Add DOCKER_CONFIG env to avoid authorization issue
  task/jib-maven/0.1/jib-maven.yaml
Labels: approved, lgtm, size/XS

#492 Bump images to 0.15.2
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.1/git-clone.yaml
  task/kaniko/0.1/kaniko.yaml
  task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
  task/pull-request/0.1/pull-request.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#433 Remove implicit "set -x" from git-clone, deleteExisting by default
  task/git-clone/0.2/README.md
  task/git-clone/0.2/git-clone.yaml
  task/git-clone/0.2/samples/git-clone-checking-out-a-branch.yaml
  task/git-clone/0.2/samples/git-clone-checking-out-a-commit.yaml
  task/git-clone/0.2/samples/using-git-clone-result.yaml
  task/git-clone/0.2/tests/run.yaml
Labels: approved, lgtm, size/XL

#494 Fix kaniko task failing issue
  task/kaniko/0.1/kaniko.yaml
Labels: approved, lgtm, size/XS

#485 Fix CI issues
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#319 Add Canary Release Task using K8s and Istio
  task/istio-canary-release/0.1/README.md
  task/istio-canary-release/0.1/istio-canary-release.yaml
  task/istio-canary-release/0.1/samples/application/app-gateway.yaml
  task/istio-canary-release/0.1/samples/application/myapp.yaml
  task/istio-canary-release/0.1/samples/run.yaml
  task/istio-canary-release/0.1/samples/taskrun.yaml
  task/istio-canary-release/0.1/support/clusterrolebinding.yaml
Labels: approved, lgtm, ok-to-test, size/L

#496 Update step command for ansible-runner task
  task/ansible-runner/0.1/README.md
  task/ansible-runner/0.1/ansible-runner.yaml
Labels: approved, lgtm, ok-to-test, size/S

#469 feat: send to Webex
  task/send-to-webex-room/0.1/README.md
  task/send-to-webex-room/0.1/send-to-webex-room.yaml
Labels: approved, lgtm, ok-to-test, size/L

#471 Update paketo builders location to dockerhub
  task/buildpacks-phases/0.1/README.md
  task/buildpacks/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/S

#491 [Fixes #481] remove add registry sidecar from docker-build tests
  task/docker-build/0.1/docker-build.yaml
  task/docker-build/0.1/tests/pre-apply-task-hook.sh
  task/docker-build/0.1/tests/resources.yaml
  task/docker-build/0.1/tests/run.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/M
