Repository tektoncd/catalog, pull requests merged in 2020-05, with the labels that each got.

#251 Add a kubeconfig-creator Task to access cluster
  kubeconfig-creator/README.md
  kubeconfig-creator/example/pers-vol.yaml
  kubeconfig-creator/example/pipeline.yaml
  kubeconfig-creator/example/pipelinerun.yaml
  kubeconfig-creator/example/test-task.yaml
  kubeconfig-creator/kubeconfig-creator.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#284 Add Kythe golang extractor task.
  kythe/README.md
  kythe/kythe-go.yaml
  kythe/tests/run.yaml
Labels: approved, cla: yes, lgtm, size/M

#295 Bump plumbing to recent master 👼
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#299 Add OpenShift Client Python task
  openshift-client-python/Dockerfile
  openshift-client-python/README.md
  openshift-client-python/openshift-client-python.yaml
Labels: approved, lgtm, ok-to-test, size/L

#304 Give test Runs time to appear in `kubectl get` lists
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#292 Add OpenShift Provisioning Task
  openshift-provision/README.md
  openshift-provision/example/pvc.yaml
  openshift-provision/example/secrets/aws-credentials.yaml
  openshift-provision/example/secrets/secrets.yaml
  openshift-provision/example/taskrun/create-run.yaml
  openshift-provision/example/taskrun/destroy-run.yaml
  openshift-provision/openshift-cluster-create.yaml
  openshift-provision/openshift-cluster-destroy.yaml
Labels: approved, lgtm, ok-to-test, size/L

#291 Fix kaniko digest results 🔧
  kaniko/README.md
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/S

#293 Do not use layers in buildah task, since layer caching depends on timestamps (unreliable in a CI/CD
  buildah/buildah.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#310 Add image-digest as Result in Buildah task
  buildah/buildah.yaml
Labels: approved, lgtm, ok-to-test, size/S

#298 Update buildah to 1.14.8
  buildah/buildah.yaml
Labels: approved, lgtm, size/XS

#231 adding proxy settings to git-clone
  git/README.md
  git/git-clone.yaml
Labels: approved, lgtm, size/S

#315 Add comment about security context 🔒
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#303 Add Github Release task
  github/create-github-release/README.md
  github/create-github-release/create-github-release.yaml
  github/create-github-release/example/run.yaml
  github/create-github-release/example/secret.yaml
Labels: approved, lgtm, ok-to-test, size/L

#322 Update to Pipelines 0.12.1 for e2e tests
  test/e2e-tests.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#318 Add task to add labels in Gitlab issue
  gitlab/README.md
  gitlab/issue-add-labels.yaml
Labels: approved, lgtm, ok-to-test, size/L

#323 Correct subdirectory error in git-clone's README
  git/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#313 (master -> v1beta1) adding proxy settings to git-clone
  git/README.md
  git/git-clone.yaml
Labels: approved, kind/feature, lgtm, size/S

#327 Bump git-init image to 0.12.1
  git/git-batch-merge.yaml
  git/git-clone.yaml
Labels: approved, lgtm, size/XS

#307 README: update the notice on v1alpha1 👼
  README.md
Labels: approved, lgtm, size/XS

#328 Allow define storage driver for buildah
  buildah/buildah.yaml
Labels: approved, lgtm, size/XS

#335 Fixed Maven mirror url param description
  maven/maven.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#337 Add "ClusterRole" to aviod binding "cluster-admin"
  kubectl/README.md
  kubectl/clusterrole.yaml
  kubectl/clusterrolebinding.yaml
Labels: approved, lgtm, size/M

#343 Update README.md
  kaniko/README.md
Labels: approved, lgtm, ok-to-test, size/XS
