Repository tektoncd/catalog, pull requests merged in 2020-01, with the labels that each got.

#165 Remove Default for ARGS and Update Image Tag to 2.0.78 for Azure CLI
  azure-cli/README.md
  azure-cli/azure_cli.yaml
  tkn/README.md
Labels: approved, lgtm, size/XS

#166 Change to ${OW_ACTION_CODE} for new Tekton version
  openwhisk/openwhisk.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#167 Correct credential path of docker
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#171 Add CONTEXT param to buildah task.
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#173 Add Github set-status and add-comment tasks
  github/README.md
  github/add_comment.yaml
  github/set_status.yaml
Labels: approved, lgtm, size/L
