Repository tektoncd/catalog, pull requests merged in 2020-09, with the labels that each got.

#493 use default yaml release using google apis instead of querying github api
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#502 Use the proper path for the last release.yaml
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#503 Fix a typo
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#480 Add Task to install Tekton components using Released Tekton Operator
  task/tekton-operator-install/0.1/README.md
  task/tekton-operator-install/0.1/tekton-operator-install.yaml
Labels: approved, lgtm, size/L

#500 Adds Hub preview link in the readme
  README.md
Labels: approved, lgtm, size/XS

#501 Add a URL result to the Git clone task.
  task/git-clone/0.2/README.md
  task/git-clone/0.2/git-clone.yaml
Labels: approved, lgtm, size/XS

#506 Parallelize calls to copy from/to GCS
  task/gcs-download/0.1/gcs-download.yaml
  task/gcs-upload/0.1/gcs-upload.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#427 Update git-clone task and document changes in behaviour
  task/git-clone/0.1/README.md
  task/git-clone/0.1/git-clone.yaml
  task/git-clone/0.2/README.md
  task/git-clone/0.2/git-clone.yaml
Labels: approved, lgtm, size/S

#508 Bump images to 0.16.2
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.2/git-clone.yaml
  task/kaniko/0.1/kaniko.yaml
  task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
  task/pull-request/0.1/pull-request.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#510 Bump buildah image
  task/aws-ecr-login/0.1/samples/test-task.yaml
  task/buildah/0.1/README.md
  task/buildah/0.1/buildah.yaml
  task/s2i/0.1/s2i.yaml
Labels: approved, lgtm, size/S

#509 Fixed typo
  task/git-cli/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#504 Add Server's User to the maven task
  task/maven/0.2/README.md
  task/maven/0.2/maven.yaml
Labels: approved, lgtm, ok-to-test, size/S

#512 Fix invalid URL to Tekton Dashboard
  task/github-set-status/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#515 Fix documentation for the GitHub status task
  task/github-set-status/0.1/README.md
  task/github-set-status/0.1/github-set-status.yaml
Labels: approved, lgtm, size/M

#513 Add Github APP token task
  task/github-app-token/0.1/Dockerfile
  task/github-app-token/0.1/README.md
  task/github-app-token/0.1/github-app-token.yaml
  task/github-app-token/0.1/samples/run.yaml
  task/github-app-token/0.1/samples/secret.yaml
Labels: approved, lgtm, size/L

#521 Add task to include Black(Python Prettier)
  task/black/0.1/README.md
  task/black/0.1/black.yaml
  task/black/0.1/tests/pre-apply-task-hook.sh
  task/black/0.1/tests/resources.yaml
  task/black/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#517 gcs-generic: Make credential file optional.
  task/gcs-generic/0.1/gcs-generic.yaml
  task/gcs-generic/0.1/samples/ls-taskrun.yaml
Labels: approved, lgtm, size/S

#520 Add GoReleaser task to Catalog
  task/goreleaser/0.1/README.md
  task/goreleaser/0.1/goreleaser.yaml
  task/goreleaser/0.1/samples/run.yaml
Labels: approved, lgtm, size/L
