Repository tektoncd/catalog, pull requests merged in 2020-11, with the labels that each got.

#554 Add tests for Blue Green Deployment Task
  task/blue-green-deploy/0.1/samples/v1-deploy/blue-deployment.yaml
  task/blue-green-deploy/0.1/samples/v1-deploy/service.yaml
  task/blue-green-deploy/0.1/samples/v2-deploy/green-deployment.yaml
  task/blue-green-deploy/0.1/tests/pre-apply-task-hook.sh
  task/blue-green-deploy/0.1/tests/resources.yaml
  task/blue-green-deploy/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#551 Update buildpack task to drop privilege
  task/buildpacks/0.2/README.md
  task/buildpacks/0.2/buildpacks.yaml
  task/buildpacks/0.2/tests/pre-apply-task-hook.sh
  task/buildpacks/0.2/tests/resources.yaml
  task/buildpacks/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#573 Bump git-init version to v0.17.3
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.2/README.md
  task/git-clone/0.2/git-clone.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#541 Add codecov task
  task/codecov/0.1/README.md
  task/codecov/0.1/codecov.yaml
  task/codecov/0.1/samples/codecov.sample.yaml
  task/codecov/0.1/tests/pre-apply-task-hook.sh
  task/codecov/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#576 bumping up pipeline version
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.2/git-clone.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#579 Fix broken link
  CONTRIBUTING.md
  task/docker-build/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#581 Fix e2e script
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#582 Add values_file to helm-upgrade-from-source
  task/helm-upgrade-from-source/0.2/README.md
  task/helm-upgrade-from-source/0.2/helm-upgrade-from-source.yaml
  task/helm-upgrade-from-source/0.2/samples/helm-upgrade-from-source-task-run.yaml.tmpl
  task/helm-upgrade-from-source/0.2/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.2/tests/resources.yaml
  task/helm-upgrade-from-source/0.2/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#574 fix typo
  task/github-add-labels/0.1/github-add-labels.yaml
Labels: approved, lgtm, size/XS

#585 Add security context in create step of buildpacks
  task/buildpacks-phases/0.1/tests/run.yaml
  task/buildpacks/0.1/buildpacks.yaml
  task/buildpacks/0.2/buildpacks.yaml
  task/buildpacks/0.2/tests/run.yaml
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#587 Fix helm-upgrade-from-repo tests
  task/helm-upgrade-from-repo/0.1/samples/helm-upgrade-from-repo-task-run.yaml.tmpl
  task/helm-upgrade-from-repo/0.1/tests/run.yaml
Labels: approved, lgtm, size/XS

#588 Fix image in Skopeo-copy task
  task/skopeo-copy/0.1/skopeo-copy.yaml
Labels: approved, lgtm, size/XS

#586 Fix e2e scripts to test modified tasks
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#589 Run build step in Orka as privilege
  task/orka-full/0.1/orka-full.yaml
Labels: approved, lgtm, size/XS

#592 Update README.md
  task/kubectl-deploy-pod/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#594 Fix broken image link
  task/s2i/0.1/README.md
Labels: approved, lgtm, size/XS
