Repository tektoncd/catalog, pull requests merged in 2020-10, with the labels that each got.

#516 Add the ability to specify secret name and key
  task/github-set-status/0.2/README.md
  task/github-set-status/0.2/github-set-status.yaml
Labels: approved, lgtm, size/L

#532 docker-build - misplaced parameter prevents push
  task/docker-build/0.1/docker-build.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#534 Rework the triggers-jenkins-job
  task/trigger-jenkins-job/0.1/tests/pre-apply-task-hook.sh
  task/trigger-jenkins-job/0.1/tests/run.yaml
  task/trigger-jenkins-job/0.1/trigger-jenkins-job.yaml
Labels: approved, lgtm, size/L

#529 Add Mypy Linter for Python
  task/mypy-lint/0.1/README.md
  task/mypy-lint/0.1/mypy-lint.yaml
  task/mypy-lint/0.1/tests/pre-apply-task-hook.sh
  task/mypy-lint/0.1/tests/resources.yaml
  task/mypy-lint/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#536 Add add_task helper function for tests
  CONTRIBUTING.md
  task/ansible-runner/0.1/tests/pre-apply-task-hook.sh
  task/black/0.1/tests/pre-apply-task-hook.sh
  task/buildah/0.1/tests/pre-apply-task-hook.sh
  task/buildpacks-phases/0.1/tests/pre-apply-task-hook.sh
  task/buildpacks/0.1/tests/pre-apply-task-hook.sh
  task/check-make/0.1/tests/pre-apply-task-hook.sh
  task/docker-build/0.1/tests/pre-apply-task-hook.sh
  task/golang-build/0.1/tests/pre-apply-task-hook.sh
  task/golang-test/0.1/tests/pre-apply-task-hook.sh
  task/golangci-lint/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-repo/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.1/tests/pre-apply-task-hook.sh
  task/jib-gradle/0.1/tests/pre-apply-task-hook.sh
  task/jib-maven/0.1/tests/pre-apply-task-hook.sh
  task/kaniko/0.1/tests/pre-apply-task-hook.sh
  task/markdown-lint/0.1/tests/pre-apply-task-hook.sh
  task/maven/0.1/tests/pre-apply-task-hook.sh
  task/maven/0.2/tests/pre-apply-task-hook.sh
  task/mypy-lint/0.1/tests/pre-apply-task-hook.sh
  task/prettier/0.1/tests/pre-apply-task-hook.sh
  task/pylint/0.1/tests/pre-apply-task-hook.sh
  task/pytest/0.1/tests/pre-apply-task-hook.sh
  task/python-coverage/0.1/tests/pre-apply-task-hook.sh
  task/replace-tokens/0.1/tests/pre-apply-task-hook.sh
  task/ruby-lint/0.1/tests/pre-apply-task-hook.sh
  task/s2i/0.1/tests/pre-apply-task-hook.sh
  task/shellcheck/0.1/tests/pre-apply-task-hook.sh
  task/ts-lint/0.1/tests/pre-apply-task-hook.sh
  task/yaml-lint/0.1/tests/pre-apply-task-hook.sh
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#535 Add a test for the kubeconfig-creator task
  task/kubeconfig-creator/0.1/tests/run.yaml
Labels: approved, lgtm, size/S

#522 Pylint: use an image with pylint preinstall and don't install requirements.txt
  task/pylint/0.2/README.md
  task/pylint/0.2/pylint.yaml
  task/pylint/0.2/tests/pre-apply-task-hook.sh
  task/pylint/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#542 Fix golang-test and build issue where src is put in literal directory "$(params.package)"
  task/golang-build/0.1/golang-build.yaml
  task/golang-test/0.1/golang-test.yaml
Labels: approved, kind/bug, lgtm, size/S

#547 Bump images to 0.17.1
  task/git-batch-merge/0.2/git-batch-merge.yaml
  task/git-clone/0.2/git-clone.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#537 Add more documentation about external testing
  CONTRIBUTING.md
Labels: approved, lgtm, size/S

#499 Add support to mount kubeconfig in `tkn` task
  task/tkn/0.2/README.md
  task/tkn/0.2/samples/run-with-workspace.yaml
  task/tkn/0.2/samples/run-without-worksapce.yaml
  task/tkn/0.2/samples/secrets.yaml
  task/tkn/0.2/tkn.yaml
Labels: approved, lgtm, size/L

#553 Add manual validation check for including tests
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#552 Add tests for tkn Task
  task/tkn/0.2/tests/resources.yaml
  task/tkn/0.2/tests/run.yaml
Labels: approved, lgtm, size/M

#543 Add new generic jenkins task
  task/jenkins/0.1/README.md
  task/jenkins/0.1/jenkins.yaml
  task/jenkins/0.1/samples/run.yaml
  task/jenkins/0.1/samples/secrets.yaml
  task/jenkins/0.1/tests/pre-apply-task-hook.sh
  task/jenkins/0.1/tests/run.yaml
Labels: approved, lgtm, size/XL

#546 Improve e2e tests runner output
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#563 Readd requirements.txt install for pylint task
  task/pylint/0.2/README.md
  task/pylint/0.2/pylint.yaml
Labels: approved, lgtm, size/S

#560 Add buildah 0.2 with optional ssl certdir workspace
  task/buildah/0.2/README.md
  task/buildah/0.2/buildah.yaml
  task/buildah/0.2/samples/openshift-internal-registry.yaml
  task/buildah/0.2/tests/internal-registry/internal-registry.yaml
  task/buildah/0.2/tests/pre-apply-task-hook.sh
  task/buildah/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#385 Test tasks that only has been modified or added
  CONTRIBUTING.md
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#564 Fix buildah sample optional workspace link
  task/buildah/0.2/README.md
Labels: approved, lgtm, size/XS

#569 Detect propelry changed files when there is multiple yaml in there
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#567 pylint: make sure we expands args
  task/pylint/0.2/pylint.yaml
Labels: approved, lgtm, size/S

#570 Fix add_task common function
  test/e2e-common.sh
Labels: approved, lgtm, size/XS
