Repository tektoncd/catalog, pull requests merged in 2021-05, with the labels that each got.

#708 Add a task to publish a catalog as bundles
  task/tekton-catalog-publish/0.1/README.md
  task/tekton-catalog-publish/0.1/samples/run-with-workspace-secret.yaml
  task/tekton-catalog-publish/0.1/samples/run-without-workspace-secret.yaml
  task/tekton-catalog-publish/0.1/samples/secrets.yaml
  task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
  task/tekton-catalog-publish/0.1/tests/pre-apply-task-hook.sh
  task/tekton-catalog-publish/0.1/tests/resources.yaml
  task/tekton-catalog-publish/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#719 [tekton-publish-catalog] Fix syntax of find command
  task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
Labels: approved, lgtm, size/XS

#720 [tekton-catalog-publish] Bind the dockerconfig workspace
  task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
Labels: approved, lgtm, size/XS

#722 Removing the inputs param prefix according to the v1beta1 specs
  task/cloudevent/0.1/cloudevent.yaml
  task/cloudevent/0.1/config/task.yaml
Labels: approved, lgtm, ok-to-test, size/S

#724 Update golangci-lint to latest
  task/golangci-lint/0.1/golangci-lint.yaml
  task/golangci-lint/0.1/tests/run.yaml
Labels: approved, lgtm, size/XS

#723 Add details on using tasks from bundles
  README.md
Labels: approved, kind/documentation, lgtm, size/S

#730 Bump plumbing dependencies to fix CI
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#734 Improves url links in the README
  pipeline/build-push-gke-deploy/0.1/README.md
  task/ansible-tower-cli/0.1/README.md
  task/boskos-acquire/0.1/README.md
  task/boskos-release/0.1/README.md
  task/buildkit-daemonless/0.1/README.md
  task/buildkit/0.1/README.md
  task/buildpacks/0.1/README.md
  task/buildpacks/0.2/README.md
  task/codecov/0.1/README.md
  task/git-cli/0.1/README.md
  task/git-rebase/0.1/README.md
  task/gitlab-add-label/0.1/README.md
  task/sonarqube-scanner/0.1/README.md
Labels: approved, lgtm, size/M

#729 github-app-token allow github api url to be defined
  task/github-app-token/0.2/github-app-token.yaml
Labels: approved, lgtm, size/S
