Repository tektoncd/catalog, pull requests merged in 2021-06, with the labels that each got.

#741 Add Microsoft Teams Notification Task
  task/send-to-microsoft-teams/0.1/README.md
  task/send-to-microsoft-teams/0.1/send-to-microsoft-teams.yaml
Labels: approved, lgtm, ok-to-test, size/M

#744 Add extra possibility for username and emoij to make it more Tekton Like
  task/send-to-webhook-slack/0.1/README.md
  task/send-to-webhook-slack/0.1/send-to-webhook-slack.yaml
Labels: approved, lgtm, ok-to-test, size/S

#749 Fix getting comment with multi Lines in 0.3 version of github-add-comment
  task/github-add-comment/0.3/github-add-comment.yaml
Labels: approved, lgtm, size/XS

#637 Add non-root user support and workspace credentials to git-clone
  task/git-clone/0.4/README.md
  task/git-clone/0.4/git-clone.yaml
  task/git-clone/0.4/samples/git-clone-checking-out-a-branch.yaml
  task/git-clone/0.4/samples/git-clone-checking-out-a-commit.yaml
  task/git-clone/0.4/samples/git-clone-sparse-checkout.yaml
  task/git-clone/0.4/samples/using-git-clone-result.yaml
  task/git-clone/0.4/tests/run.yaml
Labels: approved, lgtm, size/XL

#747 Gitleaks
  task/gitleaks/0.1/README.md
  task/gitleaks/0.1/gitleaks.yaml
  task/gitleaks/0.1/samples/gitleaks.toml
  task/gitleaks/0.1/samples/pvc.yaml
  task/gitleaks/0.1/samples/run.yaml
  task/gitleaks/0.1/tests/pre-apply-task-hook.sh
  task/gitleaks/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#751 Bump jib-maven task to 0.4 to fix certs mount path
  task/jib-maven/0.4/README.md
  task/jib-maven/0.4/jib-maven.yaml
  task/jib-maven/0.4/tests/internal-registry/internal-registry.yaml
  task/jib-maven/0.4/tests/pre-apply-task-hook.sh
  task/jib-maven/0.4/tests/resources.yaml
  task/jib-maven/0.4/tests/run.yaml
Labels: approved, lgtm, size/L

#753 change config file url for gitleaks
  task/gitleaks/0.1/README.md
  task/gitleaks/0.1/samples/run.yaml
  task/gitleaks/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/S

#746 Add option to use Basic Auth
  task/github-set-status/0.2/README.md
  task/github-set-status/0.2/github-set-status.yaml
Labels: approved, lgtm, ok-to-test, size/M

#755 Add YQ Task including tests
  task/yq/0.1/README.md
  task/yq/0.1/tests/pre-apply-task-hook.sh
  task/yq/0.1/tests/resources.yaml
  task/yq/0.1/tests/run.yaml
  task/yq/0.1/yq.yaml
Labels: approved, lgtm, ok-to-test, size/L

#759 Add Github Open PR Task
  task/github-open-pr/0.1/README.md
  task/github-open-pr/0.1/github-open-pr.yaml
  task/github-open-pr/0.1/tests/fixtures/github-open-pr.yaml
  task/github-open-pr/0.1/tests/pre-apply-task-hook.sh
  task/github-open-pr/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#762 fix argocd sync and wait task
  task/argocd-task-sync-and-wait/0.1/argocd-task-sync-and-wait.yaml
Labels: approved, lgtm, size/S

#756 Update catalog e2e test runner to use Pipelines v0.25.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#758 Add task for Kube-Linter Tool
  task/kube-linter/0.1/README.md
  task/kube-linter/0.1/kube-linter.yaml
  task/kube-linter/0.1/samples/config_sample1.yaml
  task/kube-linter/0.1/samples/config_sample2.yaml
  task/kube-linter/0.1/samples/pvc.yaml
  task/kube-linter/0.1/samples/run.yaml
  task/kube-linter/0.1/tests/pre-apply-task-hook.sh
  task/kube-linter/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#764 docs: typo in script title comment
  task/github-set-status/0.2/github-set-status.yaml
Labels: approved, lgtm, ok-to-test, size/XS
