Repository tektoncd/catalog, pull requests merged in 2021-01, with the labels that each got.

#607 Update all images using openshift to latest stable 4.6
  task/blue-green-deploy/0.1/blue-green-deploy.yaml
  task/istio-canary-release/0.1/istio-canary-release.yaml
  task/kubeconfig-creator/0.1/README.md
  task/kubeconfig-creator/0.1/samples/test-task.yaml
  task/openshift-client-kubecfg/0.1/openshift-client-kubecfg.yaml
  task/openshift-client-python/0.1/Dockerfile
  task/openshift-client/0.1/openshift-client.yaml
  task/openshift-install/0.1/README.md
  task/openshift-install/0.1/openshift-install.yaml
  task/openshift-uninstall/0.1/README.md
  task/openshift-uninstall/0.1/openshift-uninstall.yaml
Labels: approved, lgtm, size/M

#605 Change test repo to cli from pipeline in golang-test task
  task/golang-test/0.1/tests/run.yaml
Labels: approved, lgtm, size/XS

#609 Add dependency checks to e2e test script
  CONTRIBUTING.md
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#613 Powershell task added
  task/powershell/0.1/README.md
  task/powershell/0.1/powershell.yaml
  task/powershell/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#614 Fix e2e script to run only tests dir
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#615 Avoid the usage of PipelineResources from s2i
  task/s2i/0.2/Dockerfile
  task/s2i/0.2/README.md
  task/s2i/0.2/s2i.yaml
  task/s2i/0.2/samples/openshift-internal-registry.yaml
  task/s2i/0.2/tests/internal-registry/internal-registry.yaml
  task/s2i/0.2/tests/pre-apply-task-hook.sh
  task/s2i/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#610 Add set of modular Orka tasks
  task/orka-deploy/0.1/README.md
  task/orka-deploy/0.1/orka-deploy.yaml
  task/orka-deploy/0.1/samples/parallel-deploy.yaml
  task/orka-deploy/0.1/samples/use-ssh-key.yaml
  task/orka-deploy/0.1/tests/mocks/orka.yaml
  task/orka-deploy/0.1/tests/mods/mod_task.py
  task/orka-deploy/0.1/tests/mods/sidecars.yaml
  task/orka-deploy/0.1/tests/mods/volumes.yaml
  task/orka-deploy/0.1/tests/pre-apply-task-hook.sh
  task/orka-deploy/0.1/tests/resources.yaml
  task/orka-deploy/0.1/tests/run.yaml
  task/orka-deploy/OWNERS
  task/orka-init/0.1/README.md
  task/orka-init/0.1/orka-init.yaml
  task/orka-init/0.1/tests/fixtures/orka.yaml
  task/orka-init/0.1/tests/resources.yaml
  task/orka-init/0.1/tests/run.yaml
  task/orka-init/OWNERS
  task/orka-teardown/0.1/README.md
  task/orka-teardown/0.1/orka-teardown.yaml
  task/orka-teardown/0.1/tests/mocks/orka.yaml
  task/orka-teardown/0.1/tests/mods/mod_task.py
  task/orka-teardown/0.1/tests/pre-apply-task-hook.sh
  task/orka-teardown/0.1/tests/resources.yaml
  task/orka-teardown/0.1/tests/run.yaml
  task/orka-teardown/OWNERS
Labels: approved, lgtm, size/XXL

#617 Fix creation of ServiceAccount in helm tasks
  task/helm-upgrade-from-repo/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.1/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.2/tests/pre-apply-task-hook.sh
Labels: approved, lgtm, size/XS

#620 Bump Tekton Pipelines to 0.20.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#621 Skip the validation of YAML if task is being removed from catalog
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#623 Add a VERSION params to openshift client task
  task/openshift-client/0.1/README.md
  task/openshift-client/0.1/openshift-client.yaml
  task/openshift-client/0.1/tests/run.yaml
Labels: approved, lgtm, size/S

#625 Proposed recommendations for authoring tasks
  recommendations.md
Labels: approved, lgtm, ok-to-test, size/L

#624 Add npm cli task
  task/npm/0.1/README.md
  task/npm/0.1/npm.yaml
  task/npm/0.1/tests/pre-apply-task-hook.sh
  task/npm/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#622 Use multi-arch tkn container image for tkn task
  task/tkn/0.1/tkn.yaml
  task/tkn/0.2/tkn.yaml
Labels: approved, lgtm, size/XS

#632 Use multi-arch alpine/git image for git-cli and git-rebase
  task/git-cli/0.1/git-cli.yaml
  task/git-rebase/0.1/git-rebase.yaml
Labels: approved, lgtm, size/XS

#630 Updates readme by redirecting Hub preview to Hub
  README.md
Labels: approved, lgtm, size/XS

#633 Bump pullrequest-init and kubeconfigwriter version to v0.20.1
  task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
  task/pull-request/0.1/pull-request.yaml
Labels: approved, lgtm, size/XS

#636 Add vinamra28 as OWNER 🦩
  OWNERS
Labels: approved, lgtm, size/XS

#635 Add optional workspaces in kubernetes-actions task
  task/kubernetes-actions/0.2/README.md
  task/kubernetes-actions/0.2/kubernetes-actions.yaml
  task/kubernetes-actions/0.2/samples/kubectl-actions-run.yaml
  task/kubernetes-actions/0.2/samples/update-deployment-image-taskrun.yaml
  task/kubernetes-actions/0.2/tests/resources.yaml
  task/kubernetes-actions/0.2/tests/run.yaml
Labels: approved, lgtm, size/L
