Repository tektoncd/catalog, pull requests merged in 2021-02, with the labels that each got.

#258 Task for creating GitHub deployments
  task/github-create-deployment/0.1/README.md
  task/github-create-deployment/0.1/github-create-deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#640 Add version 0.2 to jib-maven task
  task/jib-maven/0.2/README.md
  task/jib-maven/0.2/jib-maven.yaml
  task/jib-maven/0.2/tests/pre-apply-task-hook.sh
  task/jib-maven/0.2/tests/resources.yaml
  task/jib-maven/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#641 aws-cli: Make `secrets` workspace optional
  task/aws-cli/0.2/README.md
  task/aws-cli/0.2/aws-cli.yaml
  task/aws-cli/0.2/samples/run.yaml
  task/aws-cli/0.2/samples/secret.yaml
Labels: approved, lgtm, ok-to-test, size/L

#646 Adds context param in golangci-lint
  task/golangci-lint/0.1/README.md
  task/golangci-lint/0.1/golangci-lint.yaml
Labels: approved, lgtm, size/XS

#645 Adds context param in golang-test task
  task/golang-test/0.1/README.md
  task/golang-test/0.1/golang-test.yaml
Labels: approved, lgtm, size/XS

#647 Bump helm-upgrade-from-repo task version to 0.2
  task/helm-upgrade-from-repo/0.2/README.md
  task/helm-upgrade-from-repo/0.2/helm-upgrade-from-repo.yaml
  task/helm-upgrade-from-repo/0.2/samples/helm-upgrade-from-repo-task-run.yaml.tmpl
  task/helm-upgrade-from-repo/0.2/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-repo/0.2/tests/resources.yaml
  task/helm-upgrade-from-repo/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#648 Minor fix in README for helm-upgrade-from-repo
  task/helm-upgrade-from-repo/0.2/README.md
Labels: approved, lgtm, size/XS

#649 Fix jenkins and trigger-jenkins-job task tests
  task/jenkins/0.1/tests/pre-apply-task-hook.sh
  task/trigger-jenkins-job/0.1/tests/pre-apply-task-hook.sh
Labels: approved, lgtm, size/XS

#650 Bump Tekton Pipelines to 0.21.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#651 Add version 0.2 to jib-gradle task
  task/jib-gradle/0.2/README.md
  task/jib-gradle/0.2/jib-gradle.yaml
  task/jib-gradle/0.2/tests/pre-apply-task-hook.sh
  task/jib-gradle/0.2/tests/resources.yaml
  task/jib-gradle/0.2/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#653 Fix failing tests for orka tasks
  task/orka-deploy/0.1/tests/run.yaml
  task/orka-teardown/0.1/tests/run.yaml
Labels: approved, lgtm, size/XS

#638 add sparse clone
  task/git-clone/0.3/README.md
  task/git-clone/0.3/git-clone.yaml
  task/git-clone/0.3/samples/git-clone-checking-out-a-branch.yaml
  task/git-clone/0.3/samples/git-clone-checking-out-a-commit.yaml
  task/git-clone/0.3/samples/git-clone-sparse-checkout.yaml
  task/git-clone/0.3/samples/using-git-clone-result.yaml
  task/git-clone/0.3/tests/run.yaml
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL
