Repository tektoncd/catalog, pull requests merged in 2021-09, with the labels that each got.

#778 test/e2e: handle fixtures configmap volume correctly
  test/e2e-common.sh
Labels: lgtm, approved, size/S, ok-to-test

#821 Fix the README to reflect actual defaults.
  task/kn/0.1/README.md
Labels: kind/bug, lgtm, approved, size/XS

#823 Add new task trivy-scanner - replaces PR https://github.com/tektoncd/catalog/pull/819
  task/trivy-scanner/0.1/README.md
  task/trivy-scanner/0.1/tests/pvc.yaml
  task/trivy-scanner/0.1/tests/run.yaml
  task/trivy-scanner/0.1/trivy-scanner.yaml
  task/trivy-scanner/OWNERS
Labels: size/L, lgtm, approved

#822 Add version 0.2 with support for multiple files at once
  task/yq/0.2/README.md
  task/yq/0.2/tests/pre-apply-task-hook.sh
  task/yq/0.2/tests/resources.yaml
  task/yq/0.2/tests/run.yaml
  task/yq/0.2/yq.yaml
Labels: size/L, lgtm, approved

#820 Use secrets through volume mounts
  task/github-open-pr/0.1/github-open-pr.yaml
Labels: lgtm, approved, size/S

#743 feature: add rsync task
  task/rsync/0.1/Dockerfile
  task/rsync/0.1/README.md
  task/rsync/0.1/rsync.yaml
  task/rsync/0.1/samples/rsync-local-to-remote.yaml
  task/rsync/0.1/samples/rsync-remote-to-local.yaml
  task/rsync/0.1/samples/secret-ssh.yaml
  task/rsync/OWNERS
Labels: size/L, lgtm, approved, ok-to-test

#828 Use multi-arch go-rest-api-test image
  task/orka-full/0.1/tests/mods/mod_task.py
  test/e2e-common.sh
Labels: lgtm, approved, size/XS
