Repository tektoncd/catalog, pull requests merged in 2021-12, with the labels that each got.

#874 bump goreleaser to latest
  task/goreleaser/0.2/goreleaser.yaml
Labels: lgtm, approved, size/XS

#856 remove blanks from receivers_email
  task/sendmail/0.1/sendmail.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#873 Add DOCKER_CONFIG env variable to jib-gradle
  task/jib-gradle/0.1/jib-gradle.yaml
  task/jib-gradle/0.2/jib-gradle.yaml
  task/jib-gradle/0.3/jib-gradle.yaml
Labels: lgtm, approved, size/XS

#877 Task golang-build add extra build params allowing for static golang builds.
  task/golang-build/0.3/README.md
  task/golang-build/0.3/golang-build.yaml
  task/golang-build/0.3/tests/pre-apply-task-hook.sh
  task/golang-build/0.3/tests/resources.yaml
  task/golang-build/0.3/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#875 Don't omit params.context in source path construction
  task/golang-test/0.2/golang-test.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#867 Added comments regarding id_rsa as default filename for private key
  task/git-clone/0.5/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#880 feat: discord messaging
  task/send-to-webhook-discord/0.1/README.md
  task/send-to-webhook-discord/0.1/send-to-webhook-discord.yaml
Labels: size/L, lgtm, approved, ok-to-test
