Repository tektoncd/catalog, pull requests merged in 2021-08, with the labels that each got.

#798 Minor fix in ansible-runner readme
  task/ansible-runner/0.1/README.md
Labels: lgtm, approved, size/XS

#775 Add diff-task-version script
  hack/diff-task-version
Labels: size/L, lgtm, approved

#801 Add git-version task
  task/git-version/0.1/README.md
  task/git-version/0.1/git-version.yaml
  task/git-version/0.1/tests/pre-apply-task-hook.sh
  task/git-version/0.1/tests/resources.yaml
  task/git-version/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#792 Add image and requirements_file params to mypy task
  task/mypy-lint/0.2/README.md
  task/mypy-lint/0.2/mypy-lint.yaml
  task/mypy-lint/0.2/tests/pre-apply-task-hook.sh
  task/mypy-lint/0.2/tests/resources.yaml
  task/mypy-lint/0.2/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#793 Add image and requirements_file params to black task
  task/black/0.2/README.md
  task/black/0.2/black.yaml
  task/black/0.2/tests/resources.yaml
  task/black/0.2/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#807 Fix typo in `generate-build-id` documentation
  task/generate-build-id/0.1/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#808 Adds reference to add new Categories to existing generalized list
  README.md
Labels: lgtm, approved, size/XS

#812 Add extra params
  task/helm-upgrade-from-source/0.3/README.md
  task/helm-upgrade-from-source/0.3/helm-upgrade-from-source.yaml
  task/helm-upgrade-from-source/0.3/samples/helm-upgrade-from-source-task-run.yaml.tmpl
  task/helm-upgrade-from-source/0.3/tests/pre-apply-task-hook.sh
  task/helm-upgrade-from-source/0.3/tests/resources.yaml
  task/helm-upgrade-from-source/0.3/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#816 Add platforms annotation to github-* tasks
  task/github-add-comment/0.4/README.md
  task/github-add-comment/0.4/github-add-comment.yaml
  task/github-add-gist/0.1/README.md
  task/github-add-gist/0.1/github-add-gist.yaml
  task/github-add-labels/0.1/README.md
  task/github-add-labels/0.1/github-add-labels.yaml
  task/github-close-issue/0.2/README.md
  task/github-close-issue/0.2/github-close-issue.yaml
  task/github-create-deployment-status/0.1/README.md
  task/github-create-deployment-status/0.1/github-create-deployment-status.yaml
  task/github-create-deployment/0.2/README.md
  task/github-create-deployment/0.2/github-create-deployment.yaml
  task/github-open-pr/0.1/README.md
  task/github-open-pr/0.1/github-open-pr.yaml
  task/github-request-reviewers/0.1/README.md
  task/github-request-reviewers/0.1/github-request-reviewers.yaml
  task/github-set-status/0.2/README.md
  task/github-set-status/0.2/github-set-status.yaml
Labels: size/M, lgtm, approved

#815 Add platforms annotation to kaniko task
  task/kaniko/0.4/README.md
  task/kaniko/0.4/kaniko.yaml
Labels: lgtm, approved, size/S

#817 Add platforms annotation to send-to-* tasks
  task/send-to-channel-slack/0.1/README.md
  task/send-to-channel-slack/0.1/send-to-channel-slack.yaml
  task/send-to-microsoft-teams/0.1/README.md
  task/send-to-microsoft-teams/0.1/send-to-microsoft-teams.yaml
  task/send-to-telegram/0.1/README.md
  task/send-to-telegram/0.1/send-to-telegram.yaml
  task/send-to-webex-room/0.1/README.md
  task/send-to-webex-room/0.1/send-to-webex-room.yaml
  task/send-to-webhook-slack/0.1/README.md
  task/send-to-webhook-slack/0.1/send-to-webhook-slack.yaml
Labels: size/M, lgtm, approved

#795 Add gitlab-set-status task
  task/gitlab-set-status/0.1/README.md
  task/gitlab-set-status/0.1/gitlab-set-status.yaml
  task/gitlab-set-status/0.1/tests/fixtures/gitlab-set-status.yaml
  task/gitlab-set-status/0.1/tests/pre-apply-task-hook.sh
  task/gitlab-set-status/0.1/tests/run.yaml
Labels: size/L, lgtm, approved

#814 Add upload pypi 0.2 task
  task/upload-pypi/0.2/README.md
  task/upload-pypi/0.2/samples/run.yaml
  task/upload-pypi/0.2/tests/pre-apply-task-hook.sh
  task/upload-pypi/0.2/tests/resources.yaml
  task/upload-pypi/0.2/tests/run.yaml
  task/upload-pypi/0.2/upload-pypi.yaml
Labels: size/L, lgtm, approved, ok-to-test

#813 Bump skopeo image to v1.3.0 and buildah image to v1.18.0
  task/buildah/0.2/README.md
  task/buildah/0.2/buildah.yaml
  task/skopeo-copy/0.1/README.md
  task/skopeo-copy/0.1/skopeo-copy.yaml
Labels: lgtm, approved, size/S

#781 Add kaniko task 0.5
  task/kaniko/0.5/README.md
  task/kaniko/0.5/kaniko.yaml
  task/kaniko/0.5/tests/pre-apply-task-hook.sh
  task/kaniko/0.5/tests/resources.yaml
  task/kaniko/0.5/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test
