Repository tektoncd/catalog, pull requests merged in 2021-04, with the labels that each got.

#684 Go back to appending sidecars with python
  test/e2e-common.sh
Labels: approved, lgtm, ok-to-test, size/M

#677 Add github-create-deployment-status task
  task/github-create-deployment-status/0.1/README.md
  task/github-create-deployment-status/0.1/github-create-deployment-status.yaml
  task/github-create-deployment-status/0.1/samples/run.yaml
  task/github-create-deployment-status/0.1/samples/secret.yaml
  task/github-create-deployment-status/0.1/tests/fixtures/github-create-deployment-status.yaml
  task/github-create-deployment-status/0.1/tests/pre-apply-task-hook.sh
  task/github-create-deployment-status/0.1/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#688 Fix kn-deployer.yaml path.
  task/kn/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#690 Update catalog e2e test runner to use Pipelines version 0.23.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#692 Support Kaniko authentication via workspace
  task/kaniko/0.3/README.md
  task/kaniko/0.3/kaniko.yaml
  task/kaniko/0.3/tests/pre-apply-task-hook.sh
  task/kaniko/0.3/tests/resources.yaml
  task/kaniko/0.3/tests/run.yaml
Labels: approved, lgtm, size/L

#696 Remove extra set -x commands in e2e tests.
  task/jenkins/0.1/tests/pre-apply-task-hook.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#697 jenkins: Add set +x to test script.
  task/jenkins/0.1/tests/pre-apply-task-hook.sh
Labels: approved, lgtm, size/XS

#693 Fix e2e scripts
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#698 Add pr checkout sample for git-clone task
  task/git-clone/0.3/samples/git-clone-checkout-out-a-pr.yaml
Labels: approved, lgtm, size/M

#699 Add comments sensative looking material for usage.
  task/buildah/0.2/samples/openshift-internal-registry.yaml
  task/codecov/0.1/tests/run.yaml
  task/orka-deploy/0.1/tests/resources.yaml
  task/orka-full/0.1/tests/resources.yaml
  task/orka-init/0.1/tests/resources.yaml
  task/orka-teardown/0.1/tests/resources.yaml
Labels: approved, lgtm, size/M

#702 Update plumbing dep to pin gke version
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, size/M

#703 Add privileged permission to jib-maven task
  task/jib-maven/0.3/jib-maven.yaml
Labels: approved, lgtm, size/XS

#689 Add RH-CRDA task.
  task/redhat-codeready-dependency-analysis/0.1/README.md
  task/redhat-codeready-dependency-analysis/0.1/redhat-codeready-dependency-analysis.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/pipeline-run.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/pipeline.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/post-task-setup.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/pre-task-setup.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/secret.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/task-run.yaml
  task/redhat-codeready-dependency-analysis/0.1/samples/workspace.yaml
  task/redhat-codeready-dependency-analysis/0.1/tests/fixtures/crda-api.yaml
  task/redhat-codeready-dependency-analysis/0.1/tests/fixtures/crda-get-response.json
  task/redhat-codeready-dependency-analysis/0.1/tests/fixtures/crda-post-response.json
  task/redhat-codeready-dependency-analysis/0.1/tests/pipeline-run.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#701 Use bash instead on sh in jib-maven
  task/jib-maven/0.3/jib-maven.yaml
Labels: approved, lgtm, size/XS

#679 Add kind catalog task.
  task/kind/0.1/README.md
  task/kind/0.1/kind.yaml
  task/kind/0.1/tests/pre-apply-task-hook.sh
  task/kind/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#707 Revert "Add privileged permission to jib-maven task"
  task/jib-maven/0.3/jib-maven.yaml
Labels: approved, lgtm, size/XS

#704 Add github app token 0.2
  task/github-app-token/0.2/Dockerfile
  task/github-app-token/0.2/README.md
  task/github-app-token/0.2/github-app-token.yaml
  task/github-app-token/0.2/samples/run.yaml
  task/github-app-token/0.2/samples/secret.yaml
Labels: approved, lgtm, size/L

#709 Raise the visibility of authoring recommendations
  .github/pull_request_template.md
  CONTRIBUTING.md
  recommendations.md
Labels: approved, lgtm, ok-to-test, size/S

#712 Bump tkn image to 0.18
  task/tkn/0.2/tkn.yaml
Labels: approved, lgtm, size/XS

#713 Fix typo in sendmail readme
  task/sendmail/0.1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#711 Pass git-clone Params as EnvVars Instead
  task/git-clone/0.1/git-clone.yaml
  task/git-clone/0.2/git-clone.yaml
  task/git-clone/0.3/git-clone.yaml
Labels: approved, lgtm, size/L
