Repository tektoncd/catalog, pull requests merged in 2021-03, with the labels that each got.

#657 Choose dind image via params
  task/docker-build/0.1/README.md
  task/docker-build/0.1/docker-build.yaml
Labels: approved, lgtm, ok-to-test, size/S

#668 Fix typo in recommendations.md
  recommendations.md
Labels: approved, lgtm, ok-to-test, size/XS

#662 Run orka-init and orka-teardown as privileged
  task/orka-init/0.1/orka-init.yaml
  task/orka-teardown/0.1/orka-teardown.yaml
Labels: approved, lgtm, size/XS

#666 Add Task to post a file on Gist Github
  task/github-add-gist/0.1/README.md
  task/github-add-gist/0.1/github-add-gist.yaml
  task/github-add-gist/0.1/samples/pipeline.yaml
  task/github-add-gist/0.1/tests/fixtures/github-post-gist.yaml
  task/github-add-gist/0.1/tests/pre-apply-task-hook.sh
  task/github-add-gist/0.1/tests/resources.yaml
  task/github-add-gist/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#659 Update kaniko image v1.0.0 -> v1.5.1
  task/kaniko/0.2/README.md
  task/kaniko/0.2/kaniko.yaml
  task/kaniko/0.2/tests/pre-apply-task-hook.sh
  task/kaniko/0.2/tests/resources.yaml
  task/kaniko/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#669 Bump Tekton Pipelines to 0.22.0
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#665 use sed to add sidecar and remove python
  test/e2e-common.sh
Labels: approved, lgtm, ok-to-test, size/S

#667 Moves a pipeline `build-push-gke-deploy` from task dir to pipeline dir
  pipeline/build-push-gke-deploy/0.1/README.md
  pipeline/build-push-gke-deploy/0.1/build-push-gke-deploy.yaml
  pipeline/build-push-gke-deploy/0.1/samples/app/Dockerfile
  pipeline/build-push-gke-deploy/0.1/samples/app/app.py
  pipeline/build-push-gke-deploy/0.1/samples/app/config/app.yaml
  pipeline/build-push-gke-deploy/0.1/samples/build-push-gke-deploy-example.md
  pipeline/build-push-gke-deploy/0.1/samples/deployed-objects.png
  pipeline/build-push-gke-deploy/0.1/samples/response.png
  task/build-push-gke-deploy/0.1/build-push-gke-deploy.yaml
Labels: approved, lgtm, size/L

#664 Add github-add-comment version 0.3
  task/github-add-comment/0.3/README.md
  task/github-add-comment/0.3/github-add-comment.yaml
  task/github-add-comment/0.3/tests/fixtures/github-post-comment.yaml
  task/github-add-comment/0.3/tests/pre-apply-task-hook.sh
  task/github-add-comment/0.3/tests/run.yaml
Labels: approved, lgtm, size/L

#671 Fix broken symlink
  task/boskos-release/0.1/samples/pipelinerun.yaml
  task/boskos-release/0.1/samples/service-account.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#643 Add version 0.2 to terraform-cli task
  task/terraform-cli/0.2/README.md
  task/terraform-cli/0.2/terraform-cli.yaml
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#673 Add `refspec` param to run.yaml
  task/git-batch-merge/0.2/tests/run.yaml
Labels: approved, lgtm, size/XS

#655 Add task/buildpacks-phases/0.2
  task/buildpacks-phases/0.2/README.md
  task/buildpacks-phases/0.2/buildpacks-phases.yaml
  task/buildpacks-phases/0.2/samples/env-vars.yaml
  task/buildpacks-phases/0.2/samples/lifecycle-image.yaml
  task/buildpacks-phases/0.2/samples/results.yaml
  task/buildpacks-phases/0.2/tests/pre-apply-task-hook.sh
  task/buildpacks-phases/0.2/tests/resources.yaml
  task/buildpacks-phases/0.2/tests/run.yaml
Labels: approved, lgtm, size/XL

#654 Add task/buildpacks/0.3
  task/buildpacks/0.3/README.md
  task/buildpacks/0.3/buildpacks.yaml
  task/buildpacks/0.3/samples/env-vars.yaml
  task/buildpacks/0.3/samples/results.yaml
  task/buildpacks/0.3/tests/pre-apply-task-hook.sh
  task/buildpacks/0.3/tests/resources.yaml
  task/buildpacks/0.3/tests/run.yaml
Labels: approved, lgtm, size/L

#663 move to go modules
  Gopkg.lock
  Gopkg.toml
  deps.go
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/pipelinerun-logs/cmd/http/kodata/templates
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#674 Task to request reviewers on a GitHub PR
  task/github-request-reviewers/0.1/README.md
  task/github-request-reviewers/0.1/github-request-reviewers.yaml
  task/github-request-reviewers/0.1/tests/fixtures/github-post-comment.yaml
  task/github-request-reviewers/0.1/tests/pre-apply-task-hook.sh
  task/github-request-reviewers/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#680 Fixed message encoding to support non-ascii chars in Sendmail task
  task/sendmail/0.1/sendmail.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#675 Bump github-create-deployment version to 0.2
  task/github-create-deployment/0.2/README.md
  task/github-create-deployment/0.2/github-create-deployment.yaml
  task/github-create-deployment/0.2/tests/fixtures/github-create-deployment.yaml
  task/github-create-deployment/0.2/tests/pre-apply-task-hook.sh
  task/github-create-deployment/0.2/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L
