Repository tektoncd/catalog, pull requests merged in 2021-07, with the labels that each got.

#772 Add documentation about platform information for resources
  README.md
  recommendations.md
Labels: approved, lgtm, size/S

#771 Fixed source directory bug when not set at the default (.)
  task/pytest/0.1/README.md
  task/pytest/0.1/pytest.yaml
Labels: approved, lgtm, ok-to-test, size/S

#773 Add 0.2 git-cli task after git-clone 0.4 example
  task/git-cli/0.2/README.md
  task/git-cli/0.2/git-cli.yaml
  task/git-cli/0.2/tests/run.yaml
Labels: approved, lgtm, size/L

#769 github-set-status: use secret volume for github token
  task/github-set-status/0.2/github-set-status.yaml
Labels: approved, lgtm, ok-to-test, size/S

#685 Update roadmap for 2021
  roadmap.md
Labels: approved, lgtm, size/M

#656 Add pipeline/buildpacks/0.1
  pipeline/buildpacks/0.1/README.md
  pipeline/buildpacks/0.1/buildpacks.yaml
  pipeline/buildpacks/0.1/samples/cache-image.yaml
  pipeline/buildpacks/0.1/samples/cache-volume.yaml
  pipeline/buildpacks/0.1/samples/env-vars.yaml
  pipeline/buildpacks/0.1/samples/run-image.yaml
  pipeline/buildpacks/0.1/tests/pre-apply-task-hook.sh
  pipeline/buildpacks/0.1/tests/run.yaml
Labels: approved, lgtm, size/L

#780 updating tekton pipeline
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#782 Add Golang Fuzz Task
  task/golang-fuzz/0.1/README.md
  task/golang-fuzz/0.1/golang-fuzz.yaml
  task/golang-fuzz/0.1/tests/pre-apply-task-hook.sh
  task/golang-fuzz/0.1/tests/resources.yaml
  task/golang-fuzz/0.1/tests/run.yaml
  task/golang-fuzz/OWNERS
Labels: approved, lgtm, size/L

#786 Add platforms information for maven and jib-maven tasks
  task/jib-maven/0.4/README.md
  task/jib-maven/0.4/jib-maven.yaml
  task/maven/0.2/README.md
  task/maven/0.2/maven.yaml
Labels: approved, lgtm, size/S

#774 Add goreleaser task 0.2
  task/goreleaser/0.2/README.md
  task/goreleaser/0.2/goreleaser.yaml
  task/goreleaser/0.2/samples/run.yaml
Labels: approved, lgtm, size/L

#785 Add platforms information for helm-upgrade-from-repo and helm-upgrade-from-source tasks
  task/helm-upgrade-from-repo/0.2/README.md
  task/helm-upgrade-from-repo/0.2/helm-upgrade-from-repo.yaml
  task/helm-upgrade-from-source/0.2/README.md
  task/helm-upgrade-from-source/0.2/helm-upgrade-from-source.yaml
Labels: approved, lgtm, ok-to-test, size/S

#789 Add platforms annotation to several task
  task/git-cli/0.1/README.md
  task/git-cli/0.1/git-cli.yaml
  task/git-cli/0.2/README.md
  task/git-cli/0.2/git-cli.yaml
  task/kubeconfig-creator/0.1/README.md
  task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
  task/pull-request/0.1/README.md
  task/pull-request/0.1/pull-request.yaml
  task/tkn/0.1/README.md
  task/tkn/0.1/tkn.yaml
  task/tkn/0.2/README.md
  task/tkn/0.2/tkn.yaml
Labels: approved, lgtm, size/S

#791 Recommend versioning script instead of using configmap 📝
  recommendations.md
Labels: approved, lgtm, size/M

#788 Add flake8 task
  task/flake8/0.1/README.md
  task/flake8/0.1/flake8.yaml
  task/flake8/0.1/tests/run.yaml
  task/flake8/OWNERS
Labels: approved, lgtm, ok-to-test, size/L
