Repository tektoncd/catalog, pull requests merged in 2021-11, with the labels that each got.

#852 Make diff-task handle code blocks
  hack/diff-task-version
Labels: lgtm, approved, size/XS

#854 delete extra characters in roadmap.md file
  roadmap.md
Labels: lgtm, approved, size/XS, ok-to-test

#797 Extend catalog test script to run tests for different platforms
  test/e2e-common.sh
  test/linux-s390x.sh
Labels: size/M, lgtm, approved

#838 fix: https://github.com/tektoncd/catalog/issues/768
  task/sonarqube-scanner/0.1/sonarqube-scanner.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#857 Add platforms annotation to pylint 0.1 task
  task/pylint/0.1/README.md
  task/pylint/0.1/pylint.yaml
Labels: lgtm, approved, size/XS

#860 Add home env to kn-apply task
  task/kn-apply/0.1/kn-apply.yaml
Labels: lgtm, approved, size/XS

#859 Update contribution guide on how to bump a task/pipeline
  CONTRIBUTING.md
Labels: lgtm, approved, size/S

#865 [pytest] Fix issue when no args are passed
  task/pytest/0.1/pytest.yaml
Labels: lgtm, approved, size/XS

#862 add optional flag to ecr-login workspace
  task/aws-ecr-login/0.1/aws-ecr-login.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#869 Directory not handled in digest-to-results step
  task/jib-maven/0.1/tests/run.yaml
  task/jib-maven/0.2/tests/run.yaml
  task/jib-maven/0.3/tests/run.yaml
  task/jib-maven/0.4/jib-maven.yaml
  task/jib-maven/0.4/tests/run.yaml
Labels: lgtm, approved, size/S

#863 Add new jib-gradle version with optional arguments
  task/jib-gradle/0.3/README.md
  task/jib-gradle/0.3/jib-gradle.yaml
  task/jib-gradle/0.3/tests/pre-apply-task-hook.sh
  task/jib-gradle/0.3/tests/resources.yaml
  task/jib-gradle/0.3/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test
