Repository tektoncd/catalog, pull requests merged in 2022-01, with the labels that each got.

#888 Correct quoting in sample file
  task/kubernetes-actions/0.2/samples/update-deployment-image-taskrun.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#881 Smaller default image for github-set-status
  task/github-set-status/0.4/README.md
  task/github-set-status/0.4/github-set-status.yaml
Labels: size/L, lgtm, approved, ok-to-test

#892 Fix small issue with gcs-download README
  task/gcs-download/0.1/README.md
Labels: lgtm, approved, size/XS

#891 Add Hadolint Dockerfile Scan
  task/hadolint/0.1/README.md
  task/hadolint/0.1/hadolint.yaml
  task/hadolint/0.1/tests/pre-apply-task-hook.sh
  task/hadolint/0.1/tests/pvc.yaml
  task/hadolint/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#893 Fix Readme hadolint task 0.1
  task/hadolint/0.1/README.md
Labels: lgtm, approved, size/S, ok-to-test

#870 Add basic auth to github-add-comment
  task/github-add-comment/0.6/README.md
  task/github-add-comment/0.6/github-add-comment.yaml
  task/github-add-comment/0.6/tests/fixtures/github-post-comment.yaml
  task/github-add-comment/0.6/tests/fixtures/list-comment-response.json
  task/github-add-comment/0.6/tests/pre-apply-task-hook.sh
  task/github-add-comment/0.6/tests/run.yaml
Labels: size/L, lgtm, approved

#896 Fix pytest args
  task/pytest/0.1/pytest.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#894 Add asciidoctor Task
  task/asciidoctor/0.1/README.md
  task/asciidoctor/0.1/asciidoctor.yaml
  task/asciidoctor/0.1/tests/pre-apply-task-hook.sh
  task/asciidoctor/0.1/tests/pvc.yaml
  task/asciidoctor/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#886 Add test script to extend support for testing on ppc64le platform
  test/linux-ppc64le.sh
Labels: kind/feature, size/M, lgtm, approved, ok-to-test
