Repository tektoncd/catalog, pull requests merged in 2022-08, with the labels that each got.

#1008 Support multiple params in tasks
  task/gradle/0.2/README.md
  task/gradle/0.2/gradle.yaml
  task/gradle/0.2/tests/pre-apply-task-hook.sh
  task/gradle/0.2/tests/resources.yaml
  task/gradle/0.2/tests/run.yaml
Labels: size/L, lgtm, approved

#1029 v0.2 for orka-init task
  task/orka-init/0.2/README.md
  task/orka-init/0.2/orka-init.yaml
  task/orka-init/0.2/tests/fixtures/orka.yaml
  task/orka-init/0.2/tests/resources.yaml
  task/orka-init/0.2/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#977 Add Sonatype Nexus Lifecycle scan task to catalog
  task/nexus-lifecycle-scan/0.1/README.md
  task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yml
  task/nexus-lifecycle-scan/0.1/samples/sample-pipeline-nexus-lifecycle-scan.yml
Labels: size/L, lgtm, approved, ok-to-test

#1036 Fixed typo: kubect --> kubectl.
  task/gcloud/0.1/README.md
  task/gcloud/0.2/README.md
Labels: lgtm, approved, size/XS

#1037 Fix orka-init tests
  task/orka-init/0.1/tests/resources.yaml
  task/orka-init/0.2/tests/resources.yaml
Labels: lgtm, approved, size/S

#1035 Add gcloud task version 0.3.
  task/gcloud/0.3/README.md
  task/gcloud/0.3/gcloud.yaml
  task/gcloud/0.3/tests/config.yaml
  task/gcloud/0.3/tests/default-version.yaml
  task/gcloud/0.3/tests/gsutil-version.yaml
  task/gcloud/0.3/tests/version-test.yaml
Labels: size/L, lgtm, approved

#1027 [task][buildah] - v0.5: option to provide container registry credentials in a workspace
  task/buildah/0.5/README.md
  task/buildah/0.5/buildah.yaml
  task/buildah/0.5/samples/dockerconfig.yaml
  task/buildah/0.5/samples/openshift-internal-registry.yaml
  task/buildah/0.5/tests/internal-registry/internal-registry.yaml
  task/buildah/0.5/tests/pre-apply-task-hook.sh
  task/buildah/0.5/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#1025 [task][s2i] - v0.3: option to provide container registry credentials in a workspace
  task/s2i/0.3/Dockerfile
  task/s2i/0.3/README.md
  task/s2i/0.3/s2i.yaml
  task/s2i/0.3/samples/dockerconfig.yaml
  task/s2i/0.3/samples/openshift-internal-registry.yaml
  task/s2i/0.3/tests/internal-registry/internal-registry.yaml
  task/s2i/0.3/tests/pre-apply-task-hook.sh
  task/s2i/0.3/tests/run.yaml
Labels: lgtm, approved, size/XL, ok-to-test

#1039 Cleanup CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/L, lgtm, approved, kind/documentation

#1038 Add Googlers as OWNERS of gcloud task.
  task/gcloud/OWNERS
Labels: lgtm, approved, size/S, kind/misc

#1043 List gcloud task in all relevant categories.
  task/gcloud/0.1/gcloud.yaml
  task/gcloud/0.2/gcloud.yaml
  task/gcloud/0.3/gcloud.yaml
Labels: lgtm, approved, size/XS

#1045 Set HOME to /tekton/home for nonroot tasks
  task/git-clone/0.8/git-clone.yaml
  task/kn-apply/0.2/kn-apply.yaml
  task/kn/0.2/kn.yaml
  task/skopeo-copy/0.2/skopeo-copy.yaml
  task/tkn/0.4/tkn.yaml
Labels: lgtm, approved, size/S

#1040 Cleanup and enhance pull_request_template.
  .github/pull_request_template.md
Labels: lgtm, approved, size/S, kind/documentation

#1046 [git-clone] Update docs, samples and tests for nonroot user
  task/git-clone/0.8/README.md
  task/git-clone/0.8/samples/git-clone-checking-out-a-branch.yaml
  task/git-clone/0.8/samples/git-clone-checking-out-a-commit.yaml
  task/git-clone/0.8/samples/git-clone-for-ssl-ca.yaml
  task/git-clone/0.8/samples/git-clone-sparse-checkout.yaml
  task/git-clone/0.8/samples/using-git-clone-result.yaml
  task/git-clone/0.8/tests/run.yaml
Labels: size/M, lgtm, approved

#1057 Fixes installations instructions in readme
  task/blue-green-deploy/0.1/README.md
  task/istio-canary-release/0.1/README.md
  task/kn-apply/0.1/README.md
  task/kn-apply/0.2/README.md
  task/kn/0.1/README.md
  task/kn/0.2/README.md
Labels: lgtm, approved, size/S

#1056 Remove @sbwsg -- account deleted.
  OWNERS
  task/generate-build-id/OWNERS
Labels: lgtm, approved, size/XS, kind/cleanup

#1060 Fix name in nexus-lifecycle-scan manifest to match the directory name
  task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yaml
Labels: lgtm, approved, size/XS

#1058 Add `gcloud` test example passing args to gsutil.
  task/gcloud/0.3/tests/gsutil-version-args.yaml
Labels: lgtm, approved, size/S, kind/documentation, kind/misc

#1059 Fix markdown link resolution in PR template.
  .github/pull_request_template.md
Labels: lgtm, approved, size/S, kind/documentation, kind/misc

#1054 fix workspace name
  task/buildah/0.5/samples/dockerconfig.yaml
Labels: lgtm, approved, size/XS, ok-to-test
