Repository tektoncd/catalog, pull requests merged in 2022-10, with the labels that each got.

#1082 Add sonarqube-scanner with optioanl credentials workspace
  task/sonarqube-scanner/0.4/README.md
  task/sonarqube-scanner/0.4/samples/sonar-project.properties
  task/sonarqube-scanner/0.4/sonarqube-scanner.yaml
  task/sonarqube-scanner/0.4/tests/pre-apply-task-hook.sh
  task/sonarqube-scanner/0.4/tests/resources.yaml
  task/sonarqube-scanner/0.4/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#1065 Updating Stackrox Image-Scan fixes #1064
  task/stackrox-image-scan/0.1/stackrox-image-scan.yaml
Labels: lgtm, approved, size/XS

#1086 Use dockerconfig for buildah bud
  task/buildah/0.5/buildah.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1071 Fix kaniko for arm64 and ppc64le.
  task/kaniko/0.6/kaniko.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1087 Add vinamra28 as Artifacthub Tekton repo owner
  task/artifacthub-repo.yml
Labels: lgtm, approved, size/XS

#1010 Add fully flexible script to yq task
  task/yq/0.4/README.md
  task/yq/0.4/tests/pre-apply-task-hook.sh
  task/yq/0.4/tests/resources.yaml
  task/yq/0.4/tests/run.yaml
  task/yq/0.4/yq.yaml
Labels: size/L, lgtm, approved

#1089 double quote to prevent globbing and word splitting
  task/sonarqube-scanner/0.3/sonarqube-scanner.yaml
Labels: lgtm, approved, size/XS

#1030 v0.2 for orka-teardown task
  task/orka-teardown/0.2/README.md
  task/orka-teardown/0.2/orka-teardown.yaml
  task/orka-teardown/0.2/tests/mocks/orka.yaml
  task/orka-teardown/0.2/tests/mods/mod_task.py
  task/orka-teardown/0.2/tests/pre-apply-task-hook.sh
  task/orka-teardown/0.2/tests/resources.yaml
  task/orka-teardown/0.2/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#1033 v0.2 for orka-deploy task
  task/orka-deploy/0.2/README.md
  task/orka-deploy/0.2/orka-deploy.yaml
  task/orka-deploy/0.2/samples/parallel-deploy.yaml
  task/orka-deploy/0.2/samples/use-ssh-key.yaml
  task/orka-deploy/0.2/tests/mocks/orka.yaml
  task/orka-deploy/0.2/tests/mods/mod_task.py
  task/orka-deploy/0.2/tests/mods/sidecars.yaml
  task/orka-deploy/0.2/tests/mods/volumes.yaml
  task/orka-deploy/0.2/tests/pre-apply-task-hook.sh
  task/orka-deploy/0.2/tests/resources.yaml
  task/orka-deploy/0.2/tests/run.yaml
Labels: lgtm, approved, size/XL, ok-to-test

#1091 update goreleaser image to latest
  task/goreleaser/0.2/goreleaser.yaml
Labels: lgtm, approved, size/XS

#1094 Make directory safe only right before the git-init
  task/git-clone/0.9/git-clone.yaml
Labels: lgtm, approved, size/XS
