Repository tektoncd/catalog, pull requests merged in 2022-03, with the labels that each got.

#909 Added chains compliant kaniko task
  task/kaniko/0.6/README.md
  task/kaniko/0.6/kaniko.yaml
  task/kaniko/0.6/tests/pre-apply-task-hook.sh
  task/kaniko/0.6/tests/resources.yaml
  task/kaniko/0.6/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#942 use the version of the current task for the installation command
  task/buildah/0.3/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#943 use the correct task name
  task/kubernetes-actions/0.2/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#929 Fix API prefix path in github-add-comment task
  task/github-add-comment/0.7/README.md
  task/github-add-comment/0.7/github-add-comment.yaml
  task/github-add-comment/0.7/tests/fixtures/github-post-comment.yaml
  task/github-add-comment/0.7/tests/fixtures/list-comment-response-ghe.json
  task/github-add-comment/0.7/tests/fixtures/list-comment-response.json
  task/github-add-comment/0.7/tests/pre-apply-task-hook.sh
  task/github-add-comment/0.7/tests/run.yaml
Labels: lgtm, approved, size/XL, ok-to-test

#948 Adapt README.md to the real used builderah version quay.io/buildah/st…
  task/buildah/0.3/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#952 Parameterizing orka-image name
  task/orka-deploy/0.1/README.md
  task/orka-deploy/0.1/orka-deploy.yaml
  task/orka-full/0.1/README.md
  task/orka-full/0.1/orka-full.yaml
  task/orka-init/0.1/README.md
  task/orka-init/0.1/orka-init.yaml
  task/orka-teardown/0.1/README.md
  task/orka-teardown/0.1/orka-teardown.yaml
Labels: size/M, lgtm, approved, ok-to-test
