Repository tektoncd/catalog, pull requests merged in 2022-09, with the labels that each got.

#1072 fix: add type to argument to both grype and syft tasks
  task/grype/0.1/grype.yaml
  task/syft/0.1/syft.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1073 Add artifacthub metadata to tektoncd/catalog
  pipeline/artifacthub-repo.yml
  task/artifacthub-repo.yml
Labels: lgtm, approved, size/S

#1074 The repositoryID needs to be set for being seen as verified
  pipeline/artifacthub-repo.yml
  task/artifacthub-repo.yml
Labels: lgtm, approved, size/XS

#1075 Add zhangquan to Artifact Hub Tekton repo owner
  pipeline/artifacthub-repo.yml
  task/artifacthub-repo.yml
Labels: lgtm, approved, size/XS

#1078 Remove some OWNERs due to inactivity
  OWNERS
Labels: lgtm, approved, size/XS

#1047 orka-init 0.2 docker-image param name change
  task/orka-init/0.2/README.md
  task/orka-init/0.2/orka-init.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1048 orka-full 0.2 docker-image param name change
  task/orka-full/0.2/README.md
  task/orka-full/0.2/orka-full.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1077 e2e-tests.sh: bump to 0.40.0 pipeline release
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS, kind/misc
