Repository tektoncd/catalog, pull requests merged in 2022-02, with the labels that each got.

#876 feat(dockerslim): dockerslim sample task
  task/dockerslim-build/0.1/README.md
  task/dockerslim-build/0.1/dockerslim-build.yaml
  task/dockerslim-build/0.1/samples/dockerslim-build.yaml.tmpl
  task/dockerslim-build/0.1/tests/pre-apply-task-hook.sh
  task/dockerslim-build/0.1/tests/resources.yaml
  task/dockerslim-build/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#866 added 0.1 of pluto task
  task/pluto/0.1/README.md
  task/pluto/0.1/pluto.yaml
  task/pluto/0.1/tests/pre-apply-task-hook.sh
  task/pluto/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#922 Fix upload-pypi task version 0.2
  task/upload-pypi/0.2/upload-pypi.yaml
Labels: lgtm, approved, size/XS

#834 Add StackRox Image Scan & Image Check Tasks - Replace #783
  task/stackrox-image-check/0.1/README.md
  task/stackrox-image-check/0.1/samples/rox-pipeline.yaml
  task/stackrox-image-check/0.1/samples/rox-secrets.yaml
  task/stackrox-image-check/0.1/stackrox-image-check.yaml
  task/stackrox-image-check/OWNERS
  task/stackrox-image-scan/0.1/README.md
  task/stackrox-image-scan/0.1/samples/rox-pipeline.yaml
  task/stackrox-image-scan/0.1/samples/rox-secrets.yaml
  task/stackrox-image-scan/0.1/stackrox-image-scan.yaml
  task/stackrox-image-scan/OWNERS
Labels: size/L, lgtm, approved

#923 Fix random Usage Sample for PWSH
  task/powershell/0.1/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#911 Add V1 of gitea set status task
  task/gitea-set-status/0.1/README.md
  task/gitea-set-status/0.1/gitea-set-status.yaml
  task/gitea-set-status/0.1/tests/fixtures/gitea-post.yaml
  task/gitea-set-status/0.1/tests/pre-apply-task-hook.sh
  task/gitea-set-status/0.1/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#927 Update tests to use another repo in golang-test
  task/golang-test/0.1/tests/run.yaml
Labels: lgtm, approved, size/XS

#906 Hadolint improve ignore rules
  task/hadolint/0.1/hadolint.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#898 Change sonarqube scanner workspace name + tests
  task/sonarqube-scanner/0.2/README.md
  task/sonarqube-scanner/0.2/samples/sonar-project.properties
  task/sonarqube-scanner/0.2/sonarqube-scanner.yaml
  task/sonarqube-scanner/0.2/tests/pre-apply-task-hook.sh
  task/sonarqube-scanner/0.2/tests/resources.yaml
  task/sonarqube-scanner/0.2/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test

#933 Update the RELEASE_YAML to pipeline v0.33.0
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS

#935 Update the RELEASE_YAML to pipeline v0.33.1
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS
