Repository tektoncd/catalog, pull requests merged in 2022-04, with the labels that each got.

#959 Buildpacks: remove `securityContext.privileged` and add `dockerconfig` workspace
  task/buildpacks/0.4/README.md
  task/buildpacks/0.4/buildpacks.yaml
  task/buildpacks/0.4/samples/dockerconfig.yaml
  task/buildpacks/0.4/samples/env-vars.yaml
  task/buildpacks/0.4/samples/results.yaml
  task/buildpacks/0.4/tests/pre-apply-task-hook.sh
  task/buildpacks/0.4/tests/resources.yaml
  task/buildpacks/0.4/tests/run.yaml
Labels: lgtm, approved, size/XL, ok-to-test

#961 Update README.md
  task/ansible-tower-cli/0.1/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#936 Add datree task
  task/datree/0.1/README.md
  task/datree/0.1/datree.yaml
  task/datree/0.1/samples/pvc.yaml
  task/datree/0.1/samples/run.yaml
  task/datree/0.1/samples/secret.yaml
Labels: size/L, lgtm, approved, ok-to-test

#962 added -n to IMAGE_URL result to avoid adding a line feed
  task/kaniko/0.6/kaniko.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#920 Add Task for Gradle builds
  task/gradle/0.1/README.md
  task/gradle/0.1/gradle.yaml
  task/gradle/0.1/tests/pre-apply-task-hook.sh
  task/gradle/0.1/tests/resources.yaml
  task/gradle/0.1/tests/run.yaml
  task/gradle/OWNERS
Labels: size/L, lgtm, approved, ok-to-test

#965 Add missing default value in gcs-upload param
  task/gcs-upload/0.3/gcs-upload.yaml
Labels: lgtm, approved, size/XS

#966 add type to params (needed for openshift)
  task/argocd-task-sync-and-wait/0.2/argocd-task-sync-and-wait.yaml
Labels: lgtm, approved, size/XS, ok-to-test
