Repository tektoncd/catalog, pull requests merged in 2022-06, with the labels that each got.

#986 Update datree task description
  task/datree/0.1/datree.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#990 Use RBAC v1 instead of v1beta1 in tasks' tests
  task/ansible-runner/0.1/tests/resources.yaml
  task/blue-green-deploy/0.1/tests/resources.yaml
  task/kubernetes-actions/0.2/tests/resources.yaml
  task/tkn/0.2/tests/resources.yaml
  task/tkn/0.3/tests/resources.yaml
Labels: lgtm, approved, size/S

#982 Add task to connect a repository to an ArgoCD server
  task/argocd-task-connect-repo/0.1/README.md
  task/argocd-task-connect-repo/0.1/argocd-task-connect-repo.yaml
Labels: size/L, lgtm, approved, ok-to-test

#995 Use Multi-arch gradle image for ppc64le, s390x gradle tasks
  test/linux-ppc64le.sh
  test/linux-s390x.sh
Labels: lgtm, approved, size/XS, ok-to-test

#1001 Update git-clone task to fix custom CAs for https and bump to 0.7 version
  task/git-clone/0.7/README.md
  task/git-clone/0.7/git-clone.yaml
  task/git-clone/0.7/samples/git-clone-checking-out-a-branch.yaml
  task/git-clone/0.7/samples/git-clone-checking-out-a-commit.yaml
  task/git-clone/0.7/samples/git-clone-sparse-checkout.yaml
  task/git-clone/0.7/samples/using-git-clone-result.yaml
  task/git-clone/0.7/tests/run.yaml
Labels: lgtm, approved, size/XXL

#1007 Add samples for ssl-ca-directory
  task/git-clone/0.7/samples/git-clone-for-ssl-ca.yaml
Labels: size/M, lgtm, approved

#1006 Update readme on how to use ssl-ca-directory workspace for 0.5 and 0.6 git-clone
  task/git-clone/0.5/README.md
  task/git-clone/0.6/README.md
Labels: size/L, lgtm, approved
