Repository tektoncd/catalog, pull requests merged in 2022-11, with the labels that each got.

#1099 Bump tektoncd/plumbing to avoid CI failures
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1103 Bump CNB_PLATFORM_API version to 0.9 for buildpack task
  task/buildpacks/0.6/README.md
  task/buildpacks/0.6/buildpacks.yaml
  task/buildpacks/0.6/samples/dockerconfig.yaml
  task/buildpacks/0.6/samples/env-vars.yaml
  task/buildpacks/0.6/samples/results.yaml
  task/buildpacks/0.6/tests/pre-apply-task-hook.sh
  task/buildpacks/0.6/tests/resources.yaml
  task/buildpacks/0.6/tests/run.yaml
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#1098 Add '42Crunch REST API Static Security Testing' task to the catalog
  task/42crunch-api-security-audit/0.1/42crunch-api-security-audit.yaml
  task/42crunch-api-security-audit/0.1/README.md
  task/42crunch-api-security-audit/0.1/samples/README.md
  task/42crunch-api-security-audit/0.1/samples/git-secret.yaml
  task/42crunch-api-security-audit/0.1/samples/pipeline-run.yaml
  task/42crunch-api-security-audit/0.1/samples/pipeline.yaml
  task/42crunch-api-security-audit/0.1/samples/secret.yaml
  task/42crunch-api-security-audit/OWNERS
Labels: size/L, lgtm, approved, ok-to-test

#1102 Fix kind e2e tests
  task/kind/0.1/tests/run.yaml
Labels: lgtm, approved, size/XS

#1108 Ansinle runner image as task parameter
  task/ansible-runner/0.2/ansible-runner.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1110 Fixed typo In Readme
  task/git-clone/0.9/README.md
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation
