Repository tektoncd/catalog, pull requests merged in 2022-05, with the labels that each got.

#974 Fix pypiserver in tests of upload-pypi task
  task/upload-pypi/0.2/tests/pre-apply-task-hook.sh
Labels: lgtm, approved, size/XS

#971 updating pipeline release
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS

#972 Remove unused parameter from datree docs
  task/datree/0.1/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#955 Use environment variables in github-set-status
  task/github-set-status/0.4/github-set-status.yaml
  task/github-set-status/0.4/tests/fixtures/github-set-status-response.json
  task/github-set-status/0.4/tests/fixtures/github-set-status.yaml
  task/github-set-status/0.4/tests/pre-apply-task-hook.sh
  task/github-set-status/0.4/tests/run.yaml
Labels: size/L, lgtm, approved

#967 Ansible builder task 0.1
  task/ansible-builder/0.1/README.md
  task/ansible-builder/0.1/ansible-builder.yaml
  task/ansible-builder/0.1/samples/0-internal-registry.yaml
  task/ansible-builder/0.1/samples/1-pipeline.yaml
  task/ansible-builder/0.1/tests/pre-apply-task-hook.sh
  task/ansible-builder/0.1/tests/run.yaml
  task/ansible-builder/OWNERS
Labels: size/L, lgtm, approved, ok-to-test
