Repository tektoncd/catalog, pull requests merged in 2023-02, with the labels that each got.

#1137 Add Chmouel in Alumni
  OWNERS
Labels: lgtm, approved, size/XS, kind/misc

#1138 Remove newline character from buildah results
  task/buildah/0.5/buildah.yaml
  task/buildah/0.5/tests/run.yaml
Labels: kind/bug, lgtm, approved, size/S

#1141 Add pip.conf workspace for pylint
  task/pylint/0.3/README.md
  task/pylint/0.3/pylint.yaml
  task/pylint/0.3/tests/pre-apply-task-hook.sh
  task/pylint/0.3/tests/resources.yaml
  task/pylint/0.3/tests/run.yaml
Labels: size/L, lgtm, approved

#1140 Add PyTest version 0.2 with optional pip.conf workspace
  task/pytest/0.2/README.md
  task/pytest/0.2/pytest.yaml
  task/pytest/0.2/tests/pre-apply-task-hook.sh
  task/pytest/0.2/tests/resources.yaml
  task/pytest/0.2/tests/run.yaml
Labels: size/L, lgtm, approved

#1131 Add ko
  task/ko/0.1/README.md
  task/ko/0.1/ko.yaml
  task/ko/0.1/tests/pre-apply-task-hook.sh
  task/ko/0.1/tests/resources.yaml
  task/ko/0.1/tests/run.yaml
Labels: kind/feature, size/L, lgtm, approved, ok-to-test

#1142 Added optional workspace gradle-config
  task/gradle/0.3/README.md
  task/gradle/0.3/gradle.yaml
  task/gradle/0.3/tests/pre-apply-task-hook.sh
  task/gradle/0.3/tests/resources.yaml
  task/gradle/0.3/tests/run.yaml
Labels: size/L, lgtm, approved, ok-to-test
