Repository tektoncd/catalog, pull requests merged in 2023-03, with the labels that each got.

#1143 Fix typo in build-push-gke-deploy-example walkthrough
  pipeline/build-push-gke-deploy/0.1/samples/build-push-gke-deploy-example.md
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation

#1148 Update e2e-tests to use Pipeline v0.45.0
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS, kind/misc

#1153 Add dependabot configuration.
  .github/dependabot.yml
Labels: lgtm, approved, size/S
