Repository tektoncd/catalog, pull requests merged in 2024-12, with the labels that each got.

#1307 Update CONTRIBUTING.md (typo correction)
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS, ok-to-test

#1312 fix: groupId typo in maven (0.4) task results
  task/maven/0.4/maven.yaml
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#1311 fix(buildah): makes it able to overwrite --tls-verify on push
  task/buildah/0.9/README.md
  task/buildah/0.9/buildah.yaml
  task/buildah/0.9/samples/dockerconfig.yaml
  task/buildah/0.9/samples/openshift-internal-registry.yaml
  task/buildah/0.9/tests/internal-registry/internal-registry.yaml
  task/buildah/0.9/tests/pre-apply-task-hook.sh
  task/buildah/0.9/tests/run.yaml
Labels: kind/bug, lgtm, approved, size/XL, ok-to-test
