Repository tektoncd/catalog, pull requests merged in 2024-05, with the labels that each got.

#1258 adding anchore cli task
  task/anchore-cli/0.1/README.md
  task/anchore-cli/0.1/anchore-cli.yaml
  task/anchore-cli/0.1/samples/secret.yaml
Labels: size/L, lgtm, approved, ok-to-test

#1254 Add remote-scp new task
  task/remote-scp/0.1/README.md
  task/remote-scp/0.1/remote-scp.yaml
  task/remote-scp/0.1/samples/run.yaml
  task/remote-scp/0.1/samples/secrets.yaml
  task/remote-scp/0.1/samples/storage.yaml
Labels: size/L, lgtm, approved, ok-to-test

#1266 Fix s2i 0.3
  task/s2i/0.2/tests/run.yaml
  task/s2i/0.3/tests/run.yaml
Labels: lgtm, approved, size/XS

#1255 Fix catalog test for ppc64le
  task/gradle/0.4/tests/run.yaml
  test/linux-ppc64le.sh
Labels: lgtm, approved, size/S, ok-to-test

#1260 task: Add M2M support for rhacs-image-scan
  task/rhacs-image-scan/4.0/README.md
  task/rhacs-image-scan/4.0/rhacs-image-scan.yaml
  task/rhacs-image-scan/4.0/samples/with-api-token/pipeline.yaml
  task/rhacs-image-scan/4.0/samples/with-api-token/pipelinerun.yaml
  task/rhacs-image-scan/4.0/samples/with-api-token/secrets.yaml
  task/rhacs-image-scan/4.0/samples/with-m2m-token/pipeline.yaml
  task/rhacs-image-scan/4.0/samples/with-m2m-token/pipelinerun.yaml
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#1257 task: add short-lived token support in `rhacs-*` tasks
  task/rhacs-deployment-check/4.0/README.md
  task/rhacs-deployment-check/4.0/rhacs-deployment-check.yaml
  task/rhacs-deployment-check/4.0/samples/with-api-token/pipeline.yaml
  task/rhacs-deployment-check/4.0/samples/with-api-token/pipelinerun.yaml
  task/rhacs-deployment-check/4.0/samples/with-api-token/secrets.yaml
  task/rhacs-deployment-check/4.0/samples/with-m2m-token/pipeline.yaml
  task/rhacs-deployment-check/4.0/samples/with-m2m-token/pipelinerun.yaml
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#1265 Add new task helm-render-manifests-from-repo
  task/helm-render-manifests-from-repo/0.1/README.md
  task/helm-render-manifests-from-repo/0.1/helm-render-manifests-from-repo.yaml
  task/helm-render-manifests-from-repo/0.1/samples/helm-render-manifests-from-repo-task-run.yaml.tmpl
  task/helm-render-manifests-from-repo/0.1/tests/pre-apply-task-hook.sh
  task/helm-render-manifests-from-repo/0.1/tests/run.yaml
Labels: kind/feature, size/L, lgtm, approved, ok-to-test

#1261 task: Add M2M support for rhacs-image-check
  task/rhacs-image-check/4.0/README.md
  task/rhacs-image-check/4.0/rhacs-image-check.yaml
  task/rhacs-image-check/4.0/samples/with-api-token/pipeline.yaml
  task/rhacs-image-check/4.0/samples/with-api-token/pipelinerun.yaml
  task/rhacs-image-check/4.0/samples/with-api-token/secrets.yaml
  task/rhacs-image-check/4.0/samples/with-m2m-token/pipeline.yaml
  task/rhacs-image-check/4.0/samples/with-m2m-token/pipelinerun.yaml
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#1259 task: add rhacs M2M authenticate task
  task/rhacs-m2m-authenticate/0.1/README.md
  task/rhacs-m2m-authenticate/0.1/rhacs-m2m-authenticate.yaml
  task/rhacs-m2m-authenticate/0.1/samples/configure-m2m.md
  task/rhacs-m2m-authenticate/0.1/samples/pipeline.yaml
  task/rhacs-m2m-authenticate/0.1/samples/pipelinerun.yaml
  task/rhacs-m2m-authenticate/OWNERS
Labels: kind/feature, size/L, lgtm, approved, ok-to-test
