Repository tektoncd/catalog, pull requests merged in 2024-03, with the labels that each got.

#1236 Deprecate ansible-runner 0.2
  task/ansible-runner/0.2/ansible-runner.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1238 Deprecate ansible-builder 0.1
  task/ansible-builder/0.1/ansible-builder.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1240 Deprecate old and broken Tasks
  task/dockerslim-build/0.1/dockerslim-build.yaml
  task/golang-fuzz/0.1/golang-fuzz.yaml
  task/kythe-go/0.2/kythe-go.yaml
  task/orka-deploy/0.1/orka-deploy.yaml
  task/orka-deploy/0.2/orka-deploy.yaml
  task/orka-full/0.1/orka-full.yaml
  task/orka-full/0.2/orka-full.yaml
  task/orka-init/0.1/orka-init.yaml
  task/orka-init/0.2/orka-init.yaml
  task/orka-teardown/0.1/orka-teardown.yaml
  task/orka-teardown/0.2/orka-teardown.yaml
  task/redhat-dependency-analytics/0.1/redhat-dependency-analytics.yaml
  task/sonarqube-scanner/0.3/sonarqube-scanner.yaml
  task/sonarqube-scanner/0.4/sonarqube-scanner.yaml
Labels: lgtm, approved, size/S, kind/misc

#1235 Add First StepAction `git-clone` to the catalog
  CONTRIBUTING.md
  stepaction/git-clone/0.1/README.md
  stepaction/git-clone/0.1/git-clone.yaml
  stepaction/git-clone/0.1/samples/git-clone-checking-out-a-branch.yaml
  stepaction/git-clone/0.1/samples/git-clone-checking-out-a-commit.yaml
  stepaction/git-clone/0.1/samples/git-clone-for-ssl-ca.yaml
  stepaction/git-clone/0.1/samples/git-clone-sparse-checkout.yaml
  stepaction/git-clone/0.1/samples/using-git-clone-result.yaml
  stepaction/git-clone/0.1/tests/run.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/run-test.sh
Labels: kind/feature, lgtm, approved, size/XXL

#1241 Created StepAction tekton-catalog-publish
  stepaction/tekton-catalog-publish/0.1/README.md
  stepaction/tekton-catalog-publish/0.1/samples/run-with-workspace-secret.yaml
  stepaction/tekton-catalog-publish/0.1/samples/run-without-workspace-secret.yaml
  stepaction/tekton-catalog-publish/0.1/samples/secrets.yaml
  stepaction/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
  stepaction/tekton-catalog-publish/0.1/tests/pre-apply-task-hook.sh
  stepaction/tekton-catalog-publish/0.1/tests/run.yaml
  test/e2e-common.sh
Labels: size/L, lgtm, approved, kind/misc

#1239 Update docker image for 42Crunch task to 3.4
  task/42crunch-api-security-audit/0.2/42crunch-api-security-audit.yaml
Labels: lgtm, approved, size/XS

#1243 fix: fix command for local execution of e2e tests
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation

#1234 adding tekton task for hugo static site generator
  task/hugo/0.1/README.md
  task/hugo/0.1/hugo.yaml
  task/hugo/0.1/tests/pre-apply-task-hook.sh
  task/hugo/0.1/tests/resources.yaml
  task/hugo/0.1/tests/run.yaml
  task/hugo/OWNERS
Labels: size/L, lgtm, approved, ok-to-test
